from nicheiq.models.delivery_format import (
    DELIVERY_FORMAT_VOCAB,
    infer_delivery_format,
    normalize_delivery_format,
)
from nicheiq.models.solution_idea import BaseSolutionIdea, RawConcept


def _idea(**overrides):
    data = {
        "solution_name": "Reply Draft",
        "description": "Drafts concise support replies.",
        "value_proposition": "Reply faster.",
        "pain_points_addressed": [],
        "core_features": ["Draft reply"],
        "target_personas": ["Independent merchants"],
    }
    data.update(overrides)
    return BaseSolutionIdea.model_validate(data)


def test_delivery_format_vocabulary_is_stable():
    assert DELIVERY_FORMAT_VOCAB == (
        "web-app",
        "mobile-app",
        "desktop-app",
        "browser-extension",
        "platform-plugin",
        "api",
        "bot-assistant",
        "data-product",
        "report",
        "service",
        "physical-product",
        "other",
    )


def test_normalization_is_tolerant_but_does_not_guess_unknown_values():
    assert normalize_delivery_format(" Browser Extension ") == "browser-extension"
    assert normalize_delivery_format("Chrome extension") == "browser-extension"
    assert normalize_delivery_format("shopify app") == "platform-plugin"
    assert normalize_delivery_format("assistant") is None
    assert normalize_delivery_format("unfamiliar delivery shell") is None


def test_inference_uses_explicit_delivery_cues_and_never_defaults_to_web_app():
    assert infer_delivery_format("A Chrome extension that drafts support replies") == "browser-extension"
    assert infer_delivery_format("An iOS mobile app for field technicians") == "mobile-app"
    assert infer_delivery_format("A downloadable desktop application for Windows") == "desktop-app"
    assert infer_delivery_format("A monthly PDF benchmark report") == "report"
    assert infer_delivery_format("A tool that helps merchants reduce refunds") is None


def test_inference_abstains_for_incidental_terms():
    assert infer_delivery_format("Enriches records with API data") is None
    assert infer_delivery_format("A reporting dashboard for support teams") is None


def test_multiple_explicit_surfaces_always_resolve_other_regardless_role_prose():
    cases = (
        "A primary iOS mobile app with a companion browser extension",
        "A companion browser extension for a primary iOS mobile app",
        "The main problem browser extension users face is solved by a mobile app",
        "A companion browser extension is the primary delivery surface, alongside an iOS mobile app",
        "A mobile app and browser extension are primary delivery surfaces",
        "A mobile app and browser extension are co-primary delivery surfaces",
        "A primary iOS mobile app with a companion browser extension that produces a monthly PDF report",
        "A browser extension that exports an audit report",
        "A monthly PDF report produced by an iOS mobile app",
        "A monthly PDF report generated by an iOS mobile app",
    )

    for text in cases:
        assert infer_delivery_format(text) == "other", text


def test_repeated_mentions_of_one_distinct_surface_still_infer_it():
    assert infer_delivery_format(
        "The iOS mobile app syncs with the Android app used by field technicians"
    ) == "mobile-app"


def test_llm_models_keep_unknown_delivery_format_for_later_normalization():
    assert _idea().delivery_format is None
    idea = _idea(delivery_format="interactive kiosk")
    concept = RawConcept(
        concept_name="Reply Draft",
        one_liner="Drafts concise support replies.",
        ideation_technique="atomic_feature",
        project_type="other",
        delivery_format="interactive kiosk",
        target_keywords=["support reply writer", "reply drafting tool"],
    )

    assert idea.delivery_format == "interactive kiosk"
    assert concept.delivery_format == "interactive kiosk"
