"""GENERATED — do not edit by hand. Sync: scripts/generate_public_apis_data.py.

Free public APIs (auth: none or free key) from github.com/public-apis/public-apis.
Each entry: (name, docs_domain_or_empty). Matching rules live in
public_data_sources.py — this module is data only.
entries-sha256:5819a95c0c92a9d3
"""

PUBLIC_APIS: tuple[tuple[str, str], ...] = (
    ('AdoptAPet', 'adoptapet.com'),
    ('Axolotl', ''),
    ('Cat Facts', ''),
    ('Cataas', 'cataas.com'),
    ('Cats', 'docs.thecatapi.com'),
    ('Dog Facts', ''),
    ('Dogs', 'dog.ceo'),
    ('eBird', 'documenter.getpostman.com'),
    ('FishWatch', 'fishwatch.gov'),
    ('HTTP Cat', 'http.cat'),
    ('HTTP Dog', 'http.dog'),
    ('IUCN', 'apiv3.iucnredlist.org'),
    ('MeowFacts', ''),
    ('Movebank', ''),
    ('Petfinder', 'petfinder.com'),
    ('PlaceBear', 'placebear.com'),
    ('PlaceDog', 'place.dog'),
    ('RandomDog', 'random.dog'),
    ('RandomDuck', 'random-d.uk'),
    ('RandomFox', 'randomfox.ca'),
    ('RescueGroups', 'userguide.rescuegroups.org'),
    ('Shibe.Online', 'shibe.online'),
    ('The Dog', 'thedogapi.com'),
    ('xeno-canto', 'xeno-canto.org'),
    ('AniDB', 'iki.anidb.net'),
    ('AnimeChan', ''),
    ('AnimeFacts', ''),
    ('AnimeNewsNetwork', 'animenewsnetwork.com'),
    ('Catboy', 'catboys.com'),
    ('Danbooru Anime', 'danbooru.donmai.us'),
    ('Jikan', 'jikan.moe'),
    ('MangaDex', 'api.mangadex.org'),
    ('Mangapi', ''),
    ('NekosBest', 'docs.nekos.best'),
    ('Studio Ghibli', ''),
    ('Trace Moe', ''),
    ('Waifu.im', 'aifu.im'),
    ('Waifu.pics', 'aifu.pics'),
    ('AbuseIPDB', 'docs.abuseipdb.com'),
    ('AlienVault Open Threat Exchange (OTX)', 'otx.alienvault.com'),
    ('CAPEsandbox', ''),
    ('Google Safe Browsing', ''),
    ('MalDatabase', 'maldatabase.com'),
    ('MalShare', 'malshare.com'),
    ('MalwareBazaar', 'bazaar.abuse.ch'),
    ('Metacert', 'metacert.com'),
    ('NoPhishy', ''),
    ('Phisherman', 'phisherman.gg'),
    ('Scanii', 'docs.scanii.com'),
    ('URLhaus', 'urlhaus-api.abuse.ch'),
    ('URLScan.io', 'urlscan.io'),
    ('VirusTotal', 'docs.virustotal.com'),
    ('Web of Trust', 'support.mywot.com'),
    ('Améthyste', 'api.amethyste.moe'),
    ('Art Institute of Chicago', 'api.artic.edu'),
    ('Colormind', 'colormind.io'),
    ('ColourLovers', 'colourlovers.com'),
    ('Cooper Hewitt', 'collection.cooperhewitt.org'),
    ('DummyImage', 'dummyimage.com'),
    ('EmojiHub', ''),
    ('Europeana', 'pro.europeana.eu'),
    ('Harvard Art Museums', ''),
    ('Icon Horse', 'icon.horse'),
    ('Iconfinder', 'developer.iconfinder.com'),
    ('Icons8', 'img.icons8.com'),
    ('Lordicon', 'lordicon.com'),
    ('Metropolitan Museum of Art', ''),
    ('PHP-Noise', 'php-noise.com'),
    ('Pixel Encounter', 'pixelencounter.com'),
    ('Rijksmuseum', 'data.rijksmuseum.nl'),
    ('UpRes', 'upres.ai'),
    ('Word Cloud', 'ordcloudapi.com'),
    ('xColors', ''),
    ('Auth0', 'auth0.com'),
    ('GetOTP', 'otp.dev'),
    ('Micro User Service', 'm3o.com'),
    ('MojoAuth', 'mojoauth.com'),
    ('SAWO Labs', 'sawolabs.com'),
    ('Stytch', 'stytch.com'),
    ('Warrant', 'arrant.dev'),
    ('Bitquery', 'graphql.bitquery.io'),
    ('Blockscout', 'dev.blockscout.com'),
    ('Chainlink', 'chain.link'),
    ('Chainpoint', 'tierion.com'),
    ('Covalent', 'covalenthq.com'),
    ('Etherscan', 'etherscan.io'),
    ('Helium', 'docs.helium.com'),
    ('Nownodes', 'nownodes.io'),
    ('Steem', 'developers.steem.io'),
    ('TWZRD Agent Intel', 'intel.twzrd.xyz'),
    ('The Graph', 'thegraph.com'),
    ('Walltime', 'alltime.info'),
    ('Watchdata', 'docs.watchdata.io'),
    ('A Bíblia Digital', 'abibliadigital.com.br'),
    ('Amanah Sunnah', 'sunnah.amanahagent.cloud'),
    ('Bhagavad Gita', 'docs.bhagavadgitaapi.in'),
    ('Bhagavad Gita telugu', ''),
    ('Bible-api', 'bible-api.com'),
    ('British National Bibliography', 'bnb.data.bl.uk'),
    ('Crossref Metadata Search', ''),
    ('GurbaniNow', ''),
    ('Gutendex', 'gutendex.com'),
    ('KDP Intelligence', ''),
    ('Open Library', 'openlibrary.org'),
    ('Penguin Publishing', 'penguinrandomhouse.biz'),
    ('PoetryDB', ''),
    ('Quran', 'quran.api-docs.io'),
    ('Quran Cloud', 'alquran.cloud'),
    ('Quran-api', ''),
    ('Rig Veda', ''),
    ('Runyankole Bible', ''),
    ('The Bible', 'docs.api.bible'),
    ('Thirukkural', ''),
    ('Urantia Papers', 'urantia.dev'),
    ('Wizard World', ''),
    ('Wolne Lektury', 'olnelektury.pl'),
    ('Apache Superset', 'superset.apache.org'),
    ('Charity Search', 'charityapi.orghunter.com'),
    ('Clearbit Logo', 'clearbit.com'),
    ('Domainsdb.info', 'domainsdb.info'),
    ('Instatus', 'instatus.com'),
    ('Invovate', 'invovate.com'),
    ('Mailchimp', 'mailchimp.com'),
    ('mailjet', 'mailjet.com'),
    ('markerapi', 'markerapi.com'),
    ('Meirra', 'meirra.com'),
    ('ORB Intelligence', 'api.orb-intelligence.com'),
    ('Pick an Agency', 'pickanagency.com'),
    ('Redash', 'redash.io'),
    ('Signaliz', 'signaliz.docs.buildwithfern.com'),
    ('SwiftKanban', 'digite.com'),
    ('Tenders in Hungary', 'tenders.guru'),
    ('Tenders in Poland', 'tenders.guru'),
    ('Tenders in Romania', 'tenders.guru'),
    ('Tenders in Spain', 'tenders.guru'),
    ('Tenders in Ukraine', 'tenders.guru'),
    ('Tomba email finder', 'tomba.io'),
    ('caldays', 'caldays.com'),
    ('Calendarific', 'calendarific.com'),
    ('Checkiday - National Holiday', 'apilayer.com'),
    ('Church Calendar', 'calapi.inadiutorium.cz'),
    ('Czech Namedays Calendar', 'svatky.adresa.info'),
    ('Festivo Public Holidays', 'docs.getfestivo.com'),
    ('Hebrew Calendar', 'hebcal.com'),
    ('Holidays', 'holidayapi.com'),
    ('LectServe', 'lectserve.com'),
    ('Nager.Date', 'date.nager.at'),
    ('Namedays Calendar', 'nameday.abalin.net'),
    ('Non-Working Days', ''),
    ('Public Holidays', 'abstractapi.com'),
    ('Russian Calendar', ''),
    ('The Calendar', 'the-calendar.net'),
    ('UK Bank Holidays', 'gov.uk'),
    ('ddownload', 'ddownload.com'),
    ('File.io', 'file.io'),
    ('Filestack', 'filestack.com'),
    ('FileUp', ''),
    ('GoFile', 'gofile.io'),
    ('Gyazo', 'gyazo.com'),
    ('Imgbb', 'api.imgbb.com'),
    ('Pantry', 'getpantry.cloud'),
    ('Pastebin', 'pastebin.com'),
    ('Pinata', 'docs.pinata.cloud'),
    ('Quip', 'quip.com'),
    ('Storj', 'docs.storj.io'),
    ('The Null Pointer', '0x0.st'),
    ('Web3 Storage', 'eb3.storage'),
    ('Azure DevOps Health', 'docs.microsoft.com'),
    ('Bitrise', 'api-docs.bitrise.io'),
    ('CircleCI', 'circleci.com'),
    ('Codeship', 'docs.cloudbees.com'),
    ('Travis CI', 'docs.travis-ci.com'),
    ('Coinlayer', 'coinlayer.com'),
    ('0x', '0x.org'),
    ('1inch', '1inch.io'),
    ('Alchemy Ethereum', 'docs.alchemy.com'),
    ('Alpha (Mossland)', 'alpha.moss.land'),
    ('Binance', ''),
    ('Bitcambio', 'nova.bitcambio.com.br'),
    ('BitcoinAverage', 'apiv2.bitcoinaverage.com'),
    ('BitcoinCharts', 'bitcoincharts.com'),
    ('Bitfinex', 'docs.bitfinex.com'),
    ('BitPanda', 'developers.bitpanda.com'),
    ('Bitmex', 'bitmex.com'),
    ('Bittrex', ''),
    ('Block', 'block.io'),
    ('Block Lottos', 'blocklottos.com'),
    ('Blockchain', 'blockchain.com'),
    ('blockfrost Cardano', 'blockfrost.io'),
    ('Brave NewCoin', 'bravenewcoin.com'),
    ('btcnode.uk', 'btcnode.uk'),
    ('BtcTurk', 'docs.btcturk.com'),
    ('Bybit', ''),
    ('CoinAPI', 'docs.coinapi.io'),
    ('Coinbase', 'developers.coinbase.com'),
    ('Coinbase Pro', 'docs.pro.coinbase.com'),
    ('CoinCap', 'docs.coincap.io'),
    ('CoinDCX', 'docs.coindcx.com'),
    ('CoinDesk', 'old.coindesk.com'),
    ('CoinGecko', 'coingecko.com'),
    ('Coinigy', 'coinigy.docs.apiary.io'),
    ('Coinlib', 'coinlib.io'),
    ('Coinlore', 'coinlore.com'),
    ('CoinMarketCap', 'coinmarketcap.com'),
    ('Coinpaprika', 'api.coinpaprika.com'),
    ('CoinRanking', 'developers.coinranking.com'),
    ('Coinremitter', 'coinremitter.com'),
    ('CoinStats', 'documenter.getpostman.com'),
    ('CryptAPI', 'docs.cryptapi.io'),
    ('CryptingUp', 'cryptingup.com'),
    ('CryptoCompare', 'cryptocompare.com'),
    ('CryptoMarket', 'api.exchange.cryptomkt.com'),
    ('Cryptonator', 'cryptonator.com'),
    ('dYdX', 'docs.dydx.exchange'),
    ('Ethplorer', ''),
    ('EXMO', 'documenter.getpostman.com'),
    ('Gateio', 'gate.io'),
    ('Gemini', 'docs.gemini.com'),
    ('Hirak Exchange Rates', 'rates.hirak.site'),
    ('Huobi', ''),
    ('Hyperliquid Market Data', ''),
    ('icy.tools', 'developers.icy.tools'),
    ('Indodax', ''),
    ('INFURA Ethereum', 'infura.io'),
    ('Kraken', 'docs.kraken.com'),
    ('KuCoin', 'docs.kucoin.com'),
    ('Localbitcoins', 'localbitcoins.com'),
    ('Mempool', 'mempool.space'),
    ('MercadoBitcoin', 'mercadobitcoin.com.br'),
    ('Messari', 'messari.io'),
    ('Mexc', 'mexc.com'),
    ('Nexchange', 'nexchange2.docs.apiary.io'),
    ('Nomics', 'nomics.com'),
    ('NovaDax', 'doc.novadax.com'),
    ('OKEx', 'okex.com'),
    ('Poloniex', 'docs.poloniex.com'),
    ('PumpFunData', 'pumpfundata.com'),
    ('Solana JSON RPC', 'docs.solana.com'),
    ('Technical Analysis', 'technical-analysis-api.com'),
    ('VALR', 'docs.valr.com'),
    ('WorldCoinIndex', 'orldcoinindex.com'),
    ('ZMOK', 'zmok.io'),
    ('Currencylayer', 'currencylayer.com'),
    ('Exchangerate.host', 'exchangerate.host'),
    ('Exchangeratesapi.io', 'exchangeratesapi.io'),
    ('Fixer', 'fixer.io'),
    ('1Forge', '1forge.com'),
    ('Amdoren', 'amdoren.com'),
    ('Bank of Russia', 'cbr.ru'),
    ('Currency-api', ''),
    ('CurrencyFreaks', 'currencyfreaks.com'),
    ('CurrencyScoop', 'currencyscoop.com'),
    ('Czech National Bank', 'cnb.cz'),
    ('Economia.Awesome', 'docs.awesomeapi.com.br'),
    ('ExchangeRate-API', 'exchangerate-api.com'),
    ('Exchangerate.dev', 'exchangerate.dev'),
    ('Frankfurter', 'frankfurter.app'),
    ('FreeForexAPI', 'freeforexapi.com'),
    ('National Bank of Poland', 'api.nbp.pl'),
    ('paralelo.bo', 'paralelo.bo'),
    ('TaxID', 'taxid.dev'),
    ('VATComply.com', 'vatcomply.com'),
    ('VATlayer', 'vatlayer.com'),
    ('Lob.com', 'lob.com'),
    ('Postman Echo', 'postman-echo.com'),
    ('PurgoMalum', 'purgomalum.com'),
    ('US Autocomplete', 'smarty.com'),
    ('US Extract', 'smarty.com'),
    ('US Street Address', 'smarty.com'),
    ('24 Pull Requests', '24pullrequests.com'),
    ('Agify.io', 'agify.io'),
    ('Amazonscraperapi', 'amazonscraperapi.com'),
    ('API Grátis', 'apigratis.com.br'),
    ('ApicAgent', 'apicagent.com'),
    ('ApiFlash', 'apiflash.com'),
    ('APIs.guru', 'apis.guru'),
    ('Azure DevOps', 'docs.microsoft.com'),
    ('Base', 'base-api.io'),
    ('Beeceptor', 'beeceptor.com'),
    ('Blague.xyz', 'blague.xyz'),
    ('Blitapp', 'blitapp.com'),
    ('Blynk-Cloud', 'blynkapi.docs.apiary.io'),
    ('Bored', 'boredapi.com'),
    ('Brainshop.ai', 'brainshop.ai'),
    ('BrewPage', 'brewpage.app'),
    ('Browshot', 'browshot.com'),
    ('CDNJS', 'api.cdnjs.com'),
    ('Changelogs.md', 'changelogs.md'),
    ('Ciprand', ''),
    ('Cloudflare Trace', ''),
    ('Codex', ''),
    ('Contentful Images', 'contentful.com'),
    ('CORS Proxy', ''),
    ('CountAPI', 'countapi.xyz'),
    ('Databricks', 'docs.databricks.com'),
    ('DigitalOcean Status', 'status.digitalocean.com'),
    ('Docker Hub', 'docs.docker.com'),
    ('DomainDb Info', 'api.domainsdb.info'),
    ('DownStatus', 'isitdownstatus.com'),
    ('ExtendsClass JSON Storage', 'extendsclass.com'),
    ('GeekFlare', 'apidocs.geekflare.com'),
    ('Genderize.io', 'genderize.io'),
    ('GETPing', 'getping.info'),
    ('Ghost', 'ghost.org'),
    ('Glitterly', 'developers.glitterly.app'),
    ('Google Firebase', ''),
    ('Google Fonts', ''),
    ('Hasura', 'hasura.io'),
    ('host-t.com', 'host-t.com'),
    ('Host.io', 'host.io'),
    ('HTTP2.Pro', 'http2.pro'),
    ('Httpbin', 'httpbin.org'),
    ('Httpbin Cloudflare', 'cloudflare-quic.com'),
    ('Hipsum', 'hipsum.co'),
    ('Hunter', 'hunter.io'),
    ('IBM Text to Speech', 'cloud.ibm.com'),
    ('Icanhazepoch', 'icanhazepoch.com'),
    ('Icanhazip', 'major.io'),
    ('IFTTT', 'platform.ifttt.com'),
    ('Image-Charts', 'documentation.image-charts.com'),
    ('import.io', 'api.docs.import.io'),
    ('ip-fast.com', 'ip-fast.com'),
    ('IP2WHOIS Information Lookup', 'ip2whois.com'),
    ('ipfind.io', 'ipfind.io'),
    ('IPify', 'ipify.org'),
    ('IPinfo', 'ipinfo.io'),
    ('isitdownstatus', 'isitdownstatus.com'),
    ('jsDelivr', ''),
    ('JSON 2 JSONP', 'json2jsonp.com'),
    ('JSONbin.io', 'jsonbin.io'),
    ('JSONPlaceholder', 'jsonplaceholder.typicode.com'),
    ('Keyvalue', 'keyvalue.immanuel.co'),
    ('Kroki', 'kroki.io'),
    ('License-API', ''),
    ('Logs.to', 'logs.to'),
    ('Lua Decompiler', 'lua-decompiler.ferib.dev'),
    ('MAC address vendor lookup', 'macaddress.io'),
    ('Micro DB', 'm3o.com'),
    ('MicroENV', 'microenv.com'),
    ('Mocky', 'designer.mocky.io'),
    ('MY IP', 'myip.com'),
    ('Nationalize.io', 'nationalize.io'),
    ('NetworkCalc', 'networkcalc.com'),
    ('npm Registry', ''),
    ('OneSignal', 'documentation.onesignal.com'),
    ('Open Page Rank', 'domcop.com'),
    ('OpenGraphr', 'opengraphr.com'),
    ('OpenQR', 'openqr.uk'),
    ('oyyi', 'oyyi.xyz'),
    ('PageCDN', 'pagecdn.com'),
    ('Postman', 'postman.com'),
    ('ProxyCrawl', 'proxycrawl.com'),
    ('ProxyKingdom', 'proxykingdom.com'),
    ('Pusher Beams', 'pusher.com'),
    ('QR & Barcode', 'solsigs.com'),
    ('QR code', 'qrtag.net'),
    ('Qrcode Monkey', 'qrcode-monkey.com'),
    ('QuickChart', 'quickchart.io'),
    ('Random Stuff', 'api-docs.pgamerx.com'),
    ('Rejax', 'rejax.io'),
    ('ReqRes', 'reqres.in'),
    ('RSS feed to JSON', ''),
    ('SavePage.io', 'savepage.io'),
    ('ScrapeNinja', 'scrapeninja.net'),
    ('ScraperApi', 'scraperapi.com'),
    ('scraperBox', 'scraperbox.com'),
    ('scrapestack', 'scrapestack.com'),
    ('ScrapingAnt', 'scrapingant.com'),
    ('ScrapingDog', 'scrapingdog.com'),
    ('Screenshot', 'abstractapi.com'),
    ('ScreenshotAPI.net', 'screenshotapi.net'),
    ('Serialif Color', 'color.serialif.com'),
    ('serpstack', 'serpstack.com'),
    ('Sheetsu', 'sheetsu.com'),
    ('SHOUTCLOUD', 'shoutcloud.io'),
    ('SiteIntel', 'siteintel.duckdns.org'),
    ('Sonar', ''),
    ('Statically', 'statically.io'),
    ('Supportivekoala', 'developers.supportivekoala.com'),
    ('Suprsonic', 'suprsonic.ai'),
    ('Talordata', 'docs.talordata.com'),
    ('Thunder Client', 'thunderclient.com'),
    ('Thunderbit', 'thunderbit.com'),
    ('Tyk', 'tyk.io'),
    ('Wandbox', ''),
    ('Webclaw', 'ebclaw.io'),
    ('WebScraping.AI', 'ebscraping.ai'),
    ('ZenRows', 'zenrows.com'),
    ('Chinese Character Web', 'ccdb.hemiola.com'),
    ('Chinese Text Project', 'ctext.org'),
    ('Collins', 'api.collinsdictionary.com'),
    ('Free Dictionary', 'dictionaryapi.dev'),
    ('Indonesia Dictionary', ''),
    ('Lingua Robot', 'linguarobot.io'),
    ('Merriam-Webster', 'dictionaryapi.com'),
    ('OwlBot', 'owlbot.info'),
    ('Oxford', 'developer.oxforddictionaries.com'),
    ('Synonyms', 'synonyms.com'),
    ('Wiktionary', 'en.wiktionary.org'),
    ('Wordnik', 'developer.wordnik.com'),
    ('Words', 'ordsapi.com'),
    ('Airtable', 'airtable.com'),
    ('Api2Convert', 'api2convert.com'),
    ('apilayer pdflayer', 'pdflayer.com'),
    ('Asana', 'developers.asana.com'),
    ('BuildPDF', 'buildpdf.co'),
    ('Clockify', 'clockify.me'),
    ('CloudConvert', 'cloudconvert.com'),
    ('Cloudmersive Document and Data Conversion', 'cloudmersive.com'),
    ('Code::Stats', 'codestats.net'),
    ('CraftMyPDF', 'craftmypdf.com'),
    ('Flowdash', 'docs.flowdash.com'),
    ('Html2PDF', 'html2pdf.app'),
    ('iLovePDF', 'developer.ilovepdf.com'),
    ('Mercury', 'mercury.postlight.com'),
    ('Monday', 'api.developer.monday.com'),
    ('OCR.Space', 'ocr.space'),
    ('PandaDoc', 'developers.pandadoc.com'),
    ('PDFFleet', 'pdffleet.com'),
    ('PolyDoc', 'polydoc.tech'),
    ('PrexView', 'prexview.com'),
    ('Renderly', 'renderlyapi.com'),
    ('Rendex', 'rendex.dev'),
    ('Restpack', 'restpack.io'),
    ('Smart Image Enhancement', 'apilayer.com'),
    ('staffSign', 'staffsign.de'),
    ('Vector Express v2.0', 'vector.express'),
    ('WakaTime', 'akatime.com'),
    ('Zero Retention PDF', 'xeropdf.com'),
    ('mailboxlayer', 'mailboxlayer.com'),
    ('Cloudmersive Validate', 'cloudmersive.com'),
    ('Disify', 'disify.com'),
    ('DropMail', 'dropmail.me'),
    ('EmailJS', 'emailjs.com'),
    ('Email Validation', 'abstractapi.com'),
    ('EVA', 'eva.pingutil.com'),
    ('Guerrilla Mail', 'guerrillamail.com'),
    ('ImprovMX', 'improvmx.com'),
    ('Kickbox', 'open.kickbox.com'),
    ('Kiprio Email Validate', 'kiprio.com'),
    ('mail.gw', 'docs.mail.gw'),
    ('mail.tm', 'docs.mail.tm'),
    ('MailboxValidator', 'mailboxvalidator.com'),
    ('MailCheck.ai', 'mailcheck.ai'),
    ('Mailtrap', 'mailtrap.docs.apiary.io'),
    ('PostStack', 'poststack.dev'),
    ('Sendgrid', 'docs.sendgrid.com'),
    ('Sendinblue', 'developers.sendinblue.com'),
    ('Verifier', 'verifier.meetchopra.com'),
    ('Anycrap', 'anycrap.shop'),
    ('chucknorris.io', 'api.chucknorris.io'),
    ('Corporate Buzz Words', ''),
    ('Excuser', ''),
    ('Fun Fact', 'api.aakhilv.me'),
    ('Imgflip', 'imgflip.com'),
    ('JokeAPI', 'v2.jokeapi.dev'),
    ('justmeme.wtf', 'justmeme.wtf'),
    ('Meme Maker', ''),
    ('Memesio', 'memesio.com'),
    ('NaMoMemes', ''),
    ('PotterDB', 'docs.potterdb.com'),
    ('Random Useless Facts', 'uselessfacts.jsph.pl'),
    ('TasteDive', 'tastedive.com'),
    ('Techy', ''),
    ('Yo Momma Jokes', ''),
    ('BreezoMeter Pollen', 'docs.breezometer.com'),
    ('Carbon Interface', 'docs.carboninterface.com'),
    ('Climatiq', 'docs.climatiq.io'),
    ('Cloverly', 'cloverly.com'),
    ('CO2 Offset', 'co2offset.io'),
    ('Danish data service Energi', 'energidataservice.dk'),
    ('GrünstromIndex', 'gruenstromindex.de'),
    ('IQAir', 'iqair.com'),
    ('Luchtmeetnet', 'api-docs.luchtmeetnet.nl'),
    ('National Grid ESO', 'data.nationalgrideso.com'),
    ('OpenAQ', 'docs.openaq.org'),
    ('PM2.5 Open Data Portal', 'pm25.lass-net.org'),
    ('PM25.in', 'pm25.in'),
    ('PVWatts', 'developer.nrel.gov'),
    ('Solematica', 'solematica.it'),
    ('Srp Energy', ''),
    ('SustainMetrics', 'sustainmetrics.net'),
    ('UK Carbon Intensity', ''),
    ('Website Carbon', 'api.websitecarbon.com'),
    ('SeatGeek', 'platform.seatgeek.com'),
    ('Ticketmaster', 'developer.ticketmaster.com'),
    ('Marketstack', 'marketstack.com'),
    ('Aletheia', 'aletheiaapi.com'),
    ('Alpaca', 'alpaca.markets'),
    ('Alpha Vantage', 'alphavantage.co'),
    ('Bank Data', 'apilayer.com'),
    ('Billplz', 'billplz.com'),
    ('Binlist', 'binlist.net'),
    ('Boleto.Cloud', 'boleto.cloud'),
    ('BriefTape', 'brieftape.com'),
    ('Citi', 'sandbox.developerhub.citi.com'),
    ('CongressInvests', 'congressinvests.com'),
    ('Econdb', 'econdb.com'),
    ('EconPulse', 'econpulse.io'),
    ('Edgrapi', 'edgrapi.com'),
    ('Fed Treasury', 'fiscaldata.treasury.gov'),
    ('Finage', 'finage.co.uk'),
    ('Financial Modeling Prep', 'site.financialmodelingprep.com'),
    ('Finnhub', 'finnhub.io'),
    ('FRED', 'fred.stlouisfed.org'),
    ('Goldprice.dev', 'goldprice.dev'),
    ('Hotstoks', 'hotstoks.com'),
    ('IBANforge', 'api.ibanforge.com'),
    ('IEX Cloud', 'iexcloud.io'),
    ('IG', 'labs.ig.com'),
    ('Indian Mutual Fund', 'mfapi.in'),
    ('Intrinio', 'intrinio.com'),
    ('Klarna', 'docs.klarna.com'),
    ('MercadoPago', 'mercadopago.com.br'),
    ('Mono', 'mono.co'),
    ('Moov', 'docs.moov.io'),
    ('Nordigen', 'nordigen.com'),
    ('OpenFIGI', 'openfigi.com'),
    ('Plaid', 'plaid.com'),
    ('Polygon', 'polygon.io'),
    ('Portfolio Optimizer', 'portfoliooptimizer.io'),
    ('Razorpay IFSC', 'razorpay.com'),
    ('Real Time Finance', ''),
    ('SEC EDGAR Data', 'sec.gov'),
    ('SmartAPI', 'smartapi.angelbroking.com'),
    ('StockData', 'stockdata.org'),
    ('StockFit', 'api.stockfit.io'),
    ('Styvio', 'styvio.com'),
    ('Sugra', 'sugra.ai'),
    ('Tax Data', 'apilayer.com'),
    ('Twelve Data', 'twelvedata.com'),
    ('VAT Validation', 'abstractapi.com'),
    ('WallstreetBets', 'dashboard.nbshare.io'),
    ('Yahoo Finance', 'yahoofinanceapi.com'),
    ('BaconMockup', 'baconmockup.com'),
    ('Chomp', 'chompthis.com'),
    ('Coffee', 'coffee.alexflipnote.dev'),
    ('Edamam nutrition', 'developer.edamam.com'),
    ('Edamam recipes', 'developer.edamam.com'),
    ('Foodish', ''),
    ('Fruityvice', 'fruityvice.com'),
    ('Kroger', 'developer.kroger.com'),
    ('LCBO', 'lcboapi.com'),
    ('Open Brewery DB', 'openbrewerydb.org'),
    ('Open Food Facts', 'orld.openfoodfacts.org'),
    ('PunkAPI', 'punkapi.com'),
    ('RecipeAPI', 'recipeapi.io'),
    ('Rustybeer', ''),
    ('Spoonacular', 'spoonacular.com'),
    ('Systembolaget', 'api-portal.systembolaget.se'),
    ('TacoFancy', ''),
    ('Tasty', ''),
    ('The Report of the Week', ''),
    ('TheCocktailDB', 'thecocktaildb.com'),
    ('TheMealDB', 'themealdb.com'),
    ("What's on the menu?", ''),
    ('WhiskyHunter', 'hiskyhunter.net'),
    ('Zestful', 'zestfuldata.com'),
    ('AmiiboAPI', 'amiiboapi.com'),
    ('Animal Crossing: New Horizons', 'acnhapi.com'),
    ('Astroworld', 'api.astroworldmc.com'),
    ('Autochess VNG', ''),
    ('Barter.VG', ''),
    ('Board Game Geek', 'boardgamegeek.com'),
    ('Brawl Stars', 'developer.brawlstars.com'),
    ('Bugsnax', 'bugsnaxapi.com'),
    ('Call of Duty Mobile', ''),
    ('CheapShark', 'cheapshark.com'),
    ('Chess.com', 'chess.com'),
    ('Chuck Norris Database', 'icndb.com'),
    ('Clash of Clans', 'developer.clashofclans.com'),
    ('Clash Royale', 'developer.clashroyale.com'),
    ('Comic Vine', 'comicvine.gamespot.com'),
    ('Crafatar', 'crafatar.com'),
    ('Cross Universe', 'crossuniverse.psychpsyo.com'),
    ('Deck of Cards', 'deckofcardsapi.com'),
    ('Destiny The Game', ''),
    ('Digimon Information', ''),
    ('Digimon TCG', 'documenter.getpostman.com'),
    ('Disney', 'disneyapi.dev'),
    ('Dota 2', 'docs.opendota.com'),
    ('Dungeons and Dragons', 'dnd5eapi.co'),
    ('Dungeons and Dragons (Alternate)', 'open5e.com'),
    ('FFXIV Collect', 'ffxivcollect.com'),
    ('FIFA Ultimate Team', 'easports.com'),
    ('Final Fantasy XIV', 'xivapi.com'),
    ('Fortnite', 'fortnitetracker.com'),
    ('Forza', 'docs.forza-api.tk'),
    ('FreeToGame', 'freetogame.com'),
    ('Fun Facts', ''),
    ('FunTranslations', 'api.funtranslations.com'),
    ('GamerPower', 'gamerpower.com'),
    ('GDBrowser', 'gdbrowser.com'),
    ('Geek-Jokes', ''),
    ('Genshin Impact', 'genshin.dev'),
    ('Giant Bomb', 'giantbomb.com'),
    ('GraphQL Pokemon', ''),
    ('Guild Wars 2', 'iki.guildwars2.com'),
    ('GW2Spidy', ''),
    ('Halo', 'developer.haloapi.com'),
    ('Humble Bundle', ''),
    ('Humor', 'humorapi.com'),
    ('Hypixel', 'api.hypixel.net'),
    ('Hyrule Compendium', ''),
    ('Hytale', 'hytale-api.com'),
    ('IGDB.com', 'api-docs.igdb.com'),
    ('Jokes One', 'jokes.one'),
    ('Jservice', 'jservice.io'),
    ('Magic The Gathering', 'magicthegathering.io'),
    ('Marvel', 'developer.marvel.com'),
    ('Minecraft Server Status', 'api.mcsrvstat.us'),
    ('MMO Games', 'mmobomb.com'),
    ('mod.io', 'docs.mod.io'),
    ('Mojang', 'iki.vg'),
    ('Monster Hunter World', 'docs.mhw-db.com'),
    ('Open Trivia', 'opentdb.com'),
    ('PandaScore', 'developers.pandascore.co'),
    ('PlayerDB', 'playerdb.co'),
    ('Pokéapi', 'pokeapi.co'),
    ('PokéAPI (GraphQL)', ''),
    ('Pokémon TCG', 'pokemontcg.io'),
    ('Psychonauts', ''),
    ('PUBG', 'developer.pubg.com'),
    ('Puyo Nexus', ''),
    ('quizapi.io', 'quizapi.io'),
    ('Raider', 'raider.io'),
    ('RAWG.io', 'rawg.io'),
    ('Rick and Morty', 'rickandmortyapi.com'),
    ('Riot Games', 'developer.riotgames.com'),
    ('RPS 101', 'rps101.pythonanywhere.com'),
    ('RuneScape', 'runescape.wiki'),
    ('Sakura CardCaptor', ''),
    ('Scryfall', 'scryfall.com'),
    ('Steam', 'steamapi.xpaw.me'),
    ('SuperHeroes', 'superheroapi.com'),
    ('TCGdex', 'tcgdex.net'),
    ('TETR.IO', 'tetr.io'),
    ('Tronald Dump', 'tronalddump.io'),
    ('Universalis', 'universalis.app'),
    ('Valorant (non-official)', 'valorant-api.com'),
    ('Warface (non-official)', 'api.wfstats.cf'),
    ('Wargaming.net', 'developers.wargaming.net'),
    ('When is next MCU film', ''),
    ('xkcd', 'xkcd.com'),
    ('Yu-Gi-Oh!', 'db.ygoprodeck.com'),
    ('IPstack', 'ipstack.com'),
    ('ipapi.com', 'ipapi.com'),
    ('Actinia Grass GIS', 'actinia.mundialis.de'),
    ('administrative-divisons-db', ''),
    ('ApogeoAPI', 'apogeoapi.com'),
    ('adresse.data.gouv.fr', 'adresse.data.gouv.fr'),
    ('Airtel IP', 'sys.airtel.lv'),
    ('Apiip', 'apiip.net'),
    ('Battuta', 'battuta.medunes.net'),
    ('BdAPIs', 'bdapis.com'),
    ('BigDataCloud', 'bigdatacloud.com'),
    ('Bing Maps', 'microsoft.com'),
    ('bng2latlong', 'getthedata.com'),
    ('Cartes.io', ''),
    ('Cep.la', 'cep.la'),
    ('CitySDK', 'citysdk.eu'),
    ('Country', 'country.is'),
    ('CountryStateCity', 'countrystatecity.in'),
    ('Ducks Unlimited', 'gis.ducks.org'),
    ('GeoApi', 'api.gouv.fr'),
    ('Geoapify', 'geoapify.com'),
    ('Geocod.io', 'geocod.io'),
    ('Geocode.xyz', 'geocode.xyz'),
    ('Geocodify.com', 'geocodify.com'),
    ('Geodata.gov.gr', 'geodata.gov.gr'),
    ('GeoDataSource', 'geodatasource.com'),
    ('GeoDB Cities', 'geodb-cities-api.wirefreethought.com'),
    ('GeographQL', ''),
    ('GeoJS', 'geojs.io'),
    ('Geokeo', 'geokeo.com'),
    ('GeoNames', 'geonames.org'),
    ('geoPlugin', 'geoplugin.com'),
    ('Google Earth Engine', ''),
    ('Google Maps', ''),
    ('Graph Countries', ''),
    ('HackMyIP', 'hackmyip.com'),
    ('HelloSalut', 'fourtonfish.com'),
    ('HERE Maps', 'developer.here.com'),
    ('Hirak IP to Country', 'iplocation.hirak.site'),
    ('Hong Kong GeoData Store', 'geodata.gov.hk'),
    ('IBGE', 'servicodados.ibge.gov.br'),
    ('IP 2 Country', 'ip2country.info'),
    ('IP Address Details', 'ipinfo.io'),
    ('IP Vigilante', 'ipvigilante.com'),
    ('ip-api', 'ip-api.com'),
    ('IP-API.io', 'ip-api.io'),
    ('IP Geolocation', 'abstractapi.com'),
    ('IP2Location', 'ip2location.com'),
    ('IP2Proxy', 'ip2location.com'),
    ('ip2geo.dev', 'ip2geo.dev'),
    ('ipapi.co', 'ipapi.co'),
    ('IPGEO', 'api.techniknews.net'),
    ('ipgeolocation', 'ipgeolocation.io'),
    ('IPInfoDB', 'ipinfodb.com'),
    ('Kakao Maps', 'apis.map.kakao.com'),
    ('keycdn IP Location Finder', 'tools.keycdn.com'),
    ('Kiprio UK Postcode', 'kiprio.com'),
    ('LatLng', 'latlng.work'),
    ('LocationIQ', 'locationiq.org'),
    ('Longdo Map', 'map.longdo.com'),
    ('Mapbox', 'docs.mapbox.com'),
    ('MapQuest', 'developer.mapquest.com'),
    ('Mexico', ''),
    ('Nominatim', 'nominatim.org'),
    ('One Map, Singapore', 'onemap.gov.sg'),
    ('OnWater', 'onwater.io'),
    ('Open Topo Data', 'opentopodata.org'),
    ('OpenCage', 'opencagedata.com'),
    ('openrouteservice.org', 'openrouteservice.org'),
    ('Pinball Map', 'pinballmap.com'),
    ('positionstack', 'positionstack.com'),
    ('Postali', 'postali.app'),
    ('PostcodeData.nl', 'api.postcodedata.nl'),
    ('Postcodes.io', 'postcodes.io'),
    ('PostalCodes', 'postalcodes.info'),
    ('Queimadas INPE', 'queimadas.dgi.inpe.br'),
    ('REST Countries', 'restcountries.com'),
    ('RoadGoat Cities', 'roadgoat.com'),
    ('Rwanda Locations', ''),
    ('SLF', ''),
    ('SpotSense', 'spotsense.io'),
    ('Telize', ''),
    ('TomTom', 'developer.tomtom.com'),
    ('Uebermaps', 'uebermaps.com'),
    ('US ZipCode', 'smarty.com'),
    ('Utah AGRC', 'api.mapserv.utah.gov'),
    ('ViaCep', 'viacep.com.br'),
    ('What3Words', 'hat3words.com'),
    ('Yandex.Maps Geocoder', 'yandex.com'),
    ('ZipCodeAPI', 'zipcodeapi.com'),
    ('Zippopotam.us', 'zippopotam.us'),
    ('Ziptastic', 'ziptasticapi.com'),
    ('Bank Negara Malaysia Open Data', 'apikijangportal.bnm.gov.my'),
    ('BCLaws', 'bclaws.gov.bc.ca'),
    ('Brazil', 'brasilapi.com.br'),
    ('Brazil Central Bank Open Data', 'dadosabertos.bcb.gov.br'),
    ('Brazil Receita WS', 'receitaws.com.br'),
    ('Brazilian Chamber of Deputies Open Data', 'dadosabertos.camara.leg.br'),
    ('CPFHub', 'cpfhub.io'),
    ('Census.gov', 'census.gov'),
    ('City, Berlin', 'daten.berlin.de'),
    ('City, Gdańsk', 'ckan.multimediagdansk.pl'),
    ('City, Gdynia', 'otwartedane.gdynia.pl'),
    ('City, Helsinki', 'hri.fi'),
    ('City, Lviv', 'opendata.city-adm.lviv.ua'),
    ('City, Nantes Open Data', 'data.nantesmetropole.fr'),
    ('City, New York Open Data', 'opendata.cityofnewyork.us'),
    ('City, Prague Open Data', 'opendata.praha.eu'),
    ('City, Toronto Open Data', 'open.toronto.ca'),
    ('Code.gov', 'code.gov'),
    ('Colorado Information Marketplace', 'data.colorado.gov'),
    ('Conversor IAE CNAE', 'conversoriaecnae.es'),
    ('Data USA', 'datausa.io'),
    ('Data.gov', 'api.data.gov'),
    ('Data.parliament.uk', 'explore.data.parliament.uk'),
    ('Deutscher Bundestag DIP', 'dip.bundestag.de'),
    ('District of Columbia Open Data', 'opendata.dc.gov'),
    ('eCourtsIndia', 'ecourtsindia.com'),
    ('EPA', 'epa.gov'),
    ('FastDOL', 'fastdol.com'),
    ('FBI Wanted', 'fbi.gov'),
    ('FEC', 'api.open.fec.gov'),
    ('Federal Register', 'federalregister.gov'),
    ('Food Standards Agency', 'ratings.food.gov.uk'),
    ('Gun Policy', 'gunpolicy.org'),
    ('Indian Pincode', 'indianpincode.com'),
    ('INEI', 'iinei.inei.gob.pe'),
    ('Interpol Red Notices', 'interpol.api.bund.dev'),
    ('Istanbul (İBB) Open Data', 'data.ibb.gov.tr'),
    ('LocalGov.jp', 'localgov.jp'),
    ('National Park Service, US', 'nps.gov'),
    ('Neotimo DGFiP Mirror', 'neotimo.com'),
    ('Open Government, ACT', 'data.act.gov.au'),
    ('Open Government, Argentina', 'datos.gob.ar'),
    ('Open Government, Australia', 'data.gov.au'),
    ('Open Government, Austria', 'data.gv.at'),
    ('Open Government, Belgium', 'data.gov.be'),
    ('Open Government, Canada', 'open.canada.ca'),
    ('Open Government, Colombia', 'dane.gov.co'),
    ('Open Government, Cyprus', 'data.gov.cy'),
    ('Open Government, Czech Republic', 'data.gov.cz'),
    ('Open Government, Denmark', 'opendata.dk'),
    ('Open Government, Estonia', 'avaandmed.eesti.ee'),
    ('Open Government, Finland', 'avoindata.fi'),
    ('Open Government, France', 'data.gouv.fr'),
    ('Open Government, Germany', 'govdata.de'),
    ('Open Government, India', 'data.gov.in'),
    ('Open Government, Indonesia', 'data.go.id'),
    ('Open Government, Ireland', 'data.gov.ie'),
    ('Open Government, Italy', 'dati.gov.it'),
    ('Open Government, Korea', 'data.go.kr'),
    ('Open Government, Lithuania', 'data.gov.lt'),
    ('Open Government, Luxembourg', 'data.public.lu'),
    ('Open Government, Mexico', 'inegi.org.mx'),
    ('Open Government, Netherlands', 'data.overheid.nl'),
    ('Open Government, New South Wales', 'api.nsw.gov.au'),
    ('Open Government, New Zealand', 'data.govt.nz'),
    ('Open Government, Norway', 'data.norge.no'),
    ('Open Government, Peru', 'datosabiertos.gob.pe'),
    ('Open Government, Poland', 'dane.gov.pl'),
    ('Open Government, Portugal', 'dados.gov.pt'),
    ('Open Government, Queensland Government', 'data.qld.gov.au'),
    ('Open Government, Romania', 'data.gov.ro'),
    ('Open Government, Saudi Arabia', 'data.gov.sa'),
    ('Open Government, Singapore', 'data.gov.sg'),
    ('Open Government, Slovakia', 'data.gov.sk'),
    ('Open Government, Slovenia', 'podatki.gov.si'),
    ('Open Government, South Australian Government', 'data.sa.gov.au'),
    ('Open Government, Spain', 'datos.gob.es'),
    ('Open Government, Sweden', 'dataportal.se'),
    ('Open Government, Switzerland', 'handbook.opendata.swiss'),
    ('Open Government, Taiwan', 'data.gov.tw'),
    ('Open Government, Thailand', 'data.go.th'),
    ('Open Government, UK', 'data.gov.uk'),
    ('Open Government, USA', 'data.gov'),
    ('Open Government, Victoria State Government', 'data.vic.gov.au'),
    ('Open Government, West Australia', 'data.wa.gov.au'),
    ('OpenMercantil', 'openmercantil.es'),
    ('PRC Exam Schedule', 'api.whenisthenextboardexam.com'),
    ('Represent by Open North', 'represent.opennorth.ca'),
    ('US Presidential Election Data by TogaTech', 'uselection.togatech.org'),
    ('USA.gov', 'usa.gov'),
    ('US Federal Contracts & Grants', 'government-data-api.onrender.com'),
    ('USAspending.gov', 'api.usaspending.gov'),
    ('Clinical Trials Directory', 'trials.starfile.org'),
    ('CMS.gov', 'data.cms.gov'),
    ('Coronavirus', 'pipedream.com'),
    ('Coronavirus in the UK', 'coronavirus.data.gov.uk'),
    ('Covid Tracking Project', 'covidtracking.com'),
    ('Covid-19', 'covid19api.com'),
    ('Covid-19 Datenhub', 'npgeo-corona-npgeo-de.hub.arcgis.com'),
    ('Covid-19 Government Response', 'covidtracker.bsg.ox.ac.uk'),
    ('Covid-19 India', 'data.covid19india.org'),
    ('Covid-19 JHU CSSE', 'nuttaphat.com'),
    ('Covid-19 Live Data', ''),
    ('Covid-19 Philippines', ''),
    ('COVID-19 Tracker Canada', 'api.covid19tracker.ca'),
    ('COVID-19 Tracker Sri Lanka', 'hpb.health.gov.lk'),
    ('COVID-ID', 'data.covid19.go.id'),
    ('Cure Cancer With AI', 'curecancerwithai.com'),
    ('Dataflow Kit COVID-19', 'covid-19.dataflowkit.com'),
    ('Edamam', 'developer.edamam.com'),
    ('FoodData Central', 'fdc.nal.usda.gov'),
    ('Healthcare.gov', 'healthcare.gov'),
    ('Humanitarian Data Exchange', 'data.humdata.org'),
    ('Infermedica', 'developer.infermedica.com'),
    ('LAPIS', 'cov-spectrum.ethz.ch'),
    ('Lexigram', 'docs.lexigram.io'),
    ('Longevity World Cup', 'longevityworldcup.com'),
    ('Makeup', ''),
    ('MedlinePlus Genetics', 'medlineplus.gov'),
    ('MyVaccination', 'documenter.getpostman.com'),
    ('NPPES', 'npiregistry.cms.hhs.gov'),
    ('Nutritionix', 'developer.nutritionix.com'),
    ('Open Data NHS Scotland', 'opendata.nhs.scot'),
    ('Open Disease', 'disease.sh'),
    ('openFDA', 'open.fda.gov'),
    ('Quarantine', 'quarantine.country'),
    ('AI Dev Jobs', 'aidevboard.com'),
    ('Adzuna', 'developer.adzuna.com'),
    ('Arbeitnow', 'documenter.getpostman.com'),
    ('Careerjet', 'careerjet.com'),
    ('DevITjobs UK', 'devitjobs.uk'),
    ('Findwork', 'findwork.dev'),
    ('GraphQL Jobs', 'graphql.jobs'),
    ('HeroHunt People Search', 'herohunt.ai'),
    ('Jobs2Careers', 'api.jobs2careers.com'),
    ('Jooble', 'jooble.org'),
    ('Juju', 'juju.com'),
    ('JobDataLake', 'jobdatalake.com'),
    ('Open Skills', ''),
    ('Reed', 'reed.co.uk'),
    ('The Muse', 'themuse.com'),
    ('USAJOBS', 'developer.usajobs.gov'),
    ('WhatJobs', 'hatjobs.com'),
    ('ZipRecruiter', 'ziprecruiter.com'),
    ('AI For Thai', 'aiforthai.in.th'),
    ('Cloudmersive', 'cloudmersive.com'),
    ('DeepAI', 'deepai.org'),
    ('Deepcode', 'deepcode.ai'),
    ('Dialogflow', ''),
    ('EXUDE-API', 'uttesh.com'),
    ('GoldBean', 'goldbean-api.xyz'),
    ('Groq', 'console.groq.com'),
    ('Hirak FaceAPI', 'faceapi.hirak.site'),
    ('Hugging Face', 'huggingface.co'),
    ('Imagga', 'imagga.com'),
    ('Inferdo', ''),
    ('IPS Online', 'docs.identity.ps'),
    ('Irisnet', 'irisnet.de'),
    ('Jina AI', 'jina.ai'),
    ('Keen IO', 'keen.io'),
    ('Machinetutors', 'machinetutors.com'),
    ('MediaCraft AI', 'mediacraft-x402-api.onrender.com'),
    ('MessengerX.io', 'messengerx.rtfd.io'),
    ('NLP Cloud', 'nlpcloud.io'),
    ('Not Human Search', 'nothumansearch.ai'),
    ('OpenVisionAPI', 'openvisionapi.com'),
    ('Perspective', 'perspectiveapi.com'),
    ('Roboflow Universe', 'universe.roboflow.com'),
    ('SkyBiometry', 'skybiometry.com'),
    ('TensorFeed', 'tensorfeed.ai'),
    ('Time Door', 'timedoor.io'),
    ('Unplugg', 'unplu.gg'),
    ('WolframAlpha', 'products.wolframalpha.com'),
    ('AI Mastering', 'aimastering.com'),
    ('Bandsintown', 'app.swaggerhub.com'),
    ('Freesound', 'freesound.org'),
    ('Gaana', ''),
    ('Genrenator', 'binaryjazz.us'),
    ('iTunes Search', 'affiliate.itunes.apple.com'),
    ('JioSaavn', ''),
    ('KSoft.Si Lyrics', 'docs.ksoft.si'),
    ('LastFm', 'last.fm'),
    ('Lyrics.ovh', 'lyricsovh.docs.apiary.io'),
    ('MusicBrainz', 'musicbrainz.org'),
    ('Musixmatch', 'developer.musixmatch.com'),
    ('Napster', 'developer.napster.com'),
    ('Openwhyd', ''),
    ('Phishin', 'phish.in'),
    ('Radio Browser', 'api.radio-browser.info'),
    ('Songkick', 'songkick.com'),
    ('Songlink / Odesli', 'notion.so'),
    ('Songsterr', 'songsterr.com'),
    ('Sunor', 'docs.sunor.cc'),
    ('TheAudioDB', 'theaudiodb.com'),
    ('Vagalume', 'api.vagalume.com.br'),
    ('Verome', ''),
    ('Mediastack', 'mediastack.com'),
    ('Associated Press', 'developer.ap.org'),
    ('Chronicling America', 'chroniclingamerica.loc.gov'),
    ('Currents', 'currentsapi.services'),
    ('Florida Man', ''),
    ('GNews', 'gnews.io'),
    ('Graphs for Coronavirus', 'corona.dnsforfamily.com'),
    ('Inshorts News', ''),
    ('MarketAux', 'marketaux.com'),
    ('New York Times', 'developer.nytimes.com'),
    ('News', 'newsapi.org'),
    ('NewsData', 'newsdata.io'),
    ('NewsX', ''),
    ('Noozra', 'noozra.com'),
    ('Spaceflight News', 'spaceflightnewsapi.net'),
    ('The Guardian', 'open-platform.theguardian.com'),
    ('The Old Reader', ''),
    ('TheNews', 'thenewsapi.com'),
    ('Trove', 'trove.nla.gov.au'),
    ('18F', ''),
    ('AcreLens', 'acrelens.com'),
    ('API Setu', 'apisetu.gov.in'),
    ('Archive.org', 'archive.readme.io'),
    ('Black History Facts', 'blackhistoryapi.io'),
    ('BotsArchive', 'botsarchive.com'),
    ('Callook.info', 'callook.info'),
    ('CARTO', 'carto.com'),
    ('CollegeScoreCard.ed.gov', 'collegescorecard.ed.gov'),
    ('Enigma Public', 'developers.enigma.com'),
    ('French Address Search', 'geo.api.gouv.fr'),
    ('InfraNode', 'infranode.dev'),
    ('Joshua Project', 'api.joshuaproject.net'),
    ('K-Data Gate', ''),
    ('Kaggle', 'kaggle.com'),
    ('LinkPreview', 'linkpreview.net'),
    ('Lowy Asia Power Index', ''),
    ('Microlink.io', 'microlink.io'),
    ('ModelPartFinder Error Codes', 'modelpartfinder.com'),
    ('Nasdaq Data Link', 'docs.data.nasdaq.com'),
    ('Nobel Prize', 'nobelprize.org'),
    ('Onyx Bazaar', 'onyx-actions.onrender.com'),
    ('Open Data Minneapolis', 'opendata.minneapolismn.gov'),
    ('Open Scholarships', 'scholarships.grudged.io'),
    ('openAFRICA', 'africaopendata.org'),
    ('OpenCorporates', 'api.opencorporates.com'),
    ('OpenSanctions', 'opensanctions.org'),
    ('Pan Africa Data', 'panafricadata.com'),
    ('PeakMetrics', ''),
    ('Recreation Information Database', 'ridb.recreation.gov'),
    ('Scoop.it', 'scoop.it'),
    ('Statistics of the World', 'statisticsoftheworld.com'),
    ('Teleport', 'developers.teleport.org'),
    ('Umeå Open Data', 'opendata.umea.se'),
    ('Universities List', ''),
    ('University of Oslo', 'data.uio.no'),
    ('UPC database', 'upcdatabase.org'),
    ('Urban Observatory', 'urbanobservatory.ac.uk'),
    ('Voidly', 'voidly.ai'),
    ('Warnely', 'arnely.com'),
    ('Wikipedia', 'mediawiki.org'),
    ('Countly', 'api.count.ly'),
    ('Datamuse', 'datamuse.com'),
    ('Drupal.org', 'drupal.org'),
    ('Evil Insult Generator', 'evilinsult.com'),
    ('GitHub Contribution Chart Generator', ''),
    ('GitHub ReadMe Stats', ''),
    ('Metabase', 'metabase.com'),
    ('Shields', 'shields.io'),
    ('PatentsView', 'patentsview.org'),
    ('TIPO', 'tiponet.tipo.gov.tw'),
    ('USPTO', 'uspto.gov'),
    ('Advice Slip', 'api.adviceslip.com'),
    ('AstroWay', 'api.astroway.info'),
    ('Biriyani As A Service', 'biriyani.anoram.com'),
    ('Dev.to', 'developers.forem.com'),
    ('Dictum', ''),
    ('FavQs.com', 'favqs.com'),
    ('FOAAS', 'foaas.com'),
    ('Forismatic', 'forismatic.com'),
    ('icanhazdadjoke', 'icanhazdadjoke.com'),
    ('Inspiration', 'inspiration.goprogram.ai'),
    ('kanye.rest', 'kanye.rest'),
    ('kimiquotes', ''),
    ('Personality.fyi', 'personality.fyi'),
    ('Programming Quotes', ''),
    ('Quotable Quotes', ''),
    ('Quote Garden', ''),
    ('quoteclear', ''),
    ('Quotes on Design', 'quotesondesign.com'),
    ('Stoicism Quote', ''),
    ('They Said So Quotes', 'theysaidso.com'),
    ('Traitify', 'app.traitify.com'),
    ('Udemy(instructor)', 'udemy.com'),
    ('Vadivelu HTTP Codes', 'vadivelu.anoram.com'),
    ('Zen Quotes', 'zenquotes.io'),
    ('Numlookup', 'numlookupapi.com'),
    ('Numverify', 'numverify.com'),
    ('Phone Specification', ''),
    ('Phone Validation', 'abstractapi.com'),
    ('Veriphone', 'veriphone.io'),
    ('VeriRoute Intel', 'verirouteintel.com'),
    ('Screenshotlayer', 'screenshotlayer.com'),
    ('APITemplate.io', 'apitemplate.io'),
    ('Bruzu', 'docs.bruzu.com'),
    ('CheetahO', 'cheetaho.com'),
    ('Dagpi', 'dagpi.xyz'),
    ('Duply', 'duply.co'),
    ('DynaPictures', 'dynapictures.com'),
    ('Giphy', 'developers.giphy.com'),
    ('Image Upload', 'apilayer.com'),
    ('Imsea', ''),
    ('Lorem Picsum', 'picsum.photos'),
    ('ObjectCut', 'objectcut.com'),
    ('Pexels', 'pexels.com'),
    ('PhotoRoom', 'photoroom.com'),
    ('Pixabay', 'pixabay.com'),
    ('PlaceKeanu', 'placekeanu.com'),
    ('Readme typing SVG', ''),
    ('Remove.bg', 'remove.bg'),
    ('ReSmush.it', 'resmush.it'),
    ('Sirv', 'apidocs.sirv.com'),
    ('Wallhaven', 'allhaven.cc'),
    ('Codeforces', 'codeforces.com'),
    ('Hackerearth', 'hackerearth.com'),
    ('Judge0 CE', 'ce.judge0.com'),
    ('KONTESTS', 'kontests.net'),
    ('Mintlify', 'docs.mintlify.com'),
    ('arcsecond.io', 'api.arcsecond.io'),
    ('arXiv', 'arxiv.org'),
    ('CodeCogs', 'editor.codecogs.com'),
    ('CORE', 'core.ac.uk'),
    ('GBIF', 'gbif.org'),
    ('iDigBio', ''),
    ('inspirehep.net', ''),
    ('isEven (humor)', 'isevenapi.xyz'),
    ('ISRO', ''),
    ('ITIS', 'itis.gov'),
    ('Launch Library 2', 'thespacedevs.com'),
    ('Materials Platform for Data Science', 'mpds.io'),
    ('Minor Planet Center', 'asterank.com'),
    ('NASA', 'api.nasa.gov'),
    ('Newton', ''),
    ('Noctua', 'api.noctuasky.com'),
    ('Numbers', 'math.tools'),
    ('Ocean Facts', ''),
    ('Open Notify', 'open-notify.org'),
    ('Open Science Framework', 'developer.osf.io'),
    ('OpenAlex', 'docs.openalex.org'),
    ('Purple Air', '2.purpleair.com'),
    ('Remote Calc', ''),
    ('SHARE', 'share.osf.io'),
    ('SpaceX', ''),
    ('Sunrise and Sunset', 'sunrise-sunset.org'),
    ('Times Adder', ''),
    ('TLE', 'tle.ivanstanojevic.me'),
    ('USGS Earthquake Hazards Program', 'earthquake.usgs.gov'),
    ('USGS Water Services', 'aterservices.usgs.gov'),
    ('World Bank', 'datahelpdesk.worldbank.org'),
    ('xMath', ''),
    ('Application Environment Verification', ''),
    ('BinaryEdge', 'docs.binaryedge.io'),
    ('Botd', ''),
    ('Bugcrowd', 'docs.bugcrowd.com'),
    ('Censys', 'search.censys.io'),
    ('Classify', ''),
    ('Complete Criminal Checks', 'completecriminalchecks.com'),
    ('CRXcavator', 'crxcavator.io'),
    ('dead-drop', 'api.dead-drop.xyz'),
    ('Dehash.lt', ''),
    ('Domain Intelligence', 'oti-labs.com'),
    ('EmailRep', 'docs.emailrep.io'),
    ('Escape', ''),
    ('FilterLists', 'filterlists.com'),
    ('FingerprintJS Pro', 'dev.fingerprintjs.com'),
    ('FraudLabs Pro', 'fraudlabspro.com'),
    ('FullHunt', 'api-docs.fullhunt.io'),
    ('GitGuardian', 'api.gitguardian.com'),
    ('GreyNoise', 'docs.greynoise.io'),
    ('HackerOne', 'api.hackerone.com'),
    ('Hashable', 'hashable.space'),
    ('HaveIBeenPwned', 'haveibeenpwned.com'),
    ('Intelligence X', ''),
    ('IPLogs', 'iplogs.com'),
    ('LoginRadius', 'loginradius.com'),
    ('Microsoft Security Response Center (MSRC)', 'msrc.microsoft.com'),
    ('Mozilla http scanner', ''),
    ('Mozilla tls scanner', ''),
    ('National Vulnerability Database', 'nvd.nist.gov'),
    ('Passwordinator', ''),
    ('PhishStats', 'phishstats.info'),
    ('Privacy.com', 'privacy.com'),
    ('Pulsedive', 'pulsedive.com'),
    ('SecurityTrails', 'securitytrails.com'),
    ('Shodan', 'developer.shodan.io'),
    ('Spyse', 'spyse-dev.readme.io'),
    ('Threat Jammer', 'threatjammer.com'),
    ('UK Police', 'data.police.uk'),
    ('Virushee', 'api.virushee.com'),
    ('VulDB', 'vuldb.com'),
    ('Best Buy', ''),
    ('BuyWhere', 'buywhere.ai'),
    ('Descripio Amazon Reviews', 'docs.descripio.com'),
    ('Dummy Products', ''),
    ('Lazada', 'open.lazada.com'),
    ('Mercadolibre', 'developers.mercadolibre.cl'),
    ('Octopart', 'octopart.com'),
    ('OLX Poland', 'developer.olx.pl'),
    ('Shopee', 'open.shopee.com'),
    ('WooCommerce', ''),
    ('4chan', ''),
    ('Ayrshare', 'ayrshare.com'),
    ('aztro', 'aztro.sameerkumar.website'),
    ('Bluesky', 'docs.bsky.app'),
    ('Dangerous Discord Database', 'discord.riverside.rocks'),
    ('Doge-Meme', 'api.doge-meme.lol'),
    ('Fuck Off as a Service', 'foaas.com'),
    ('GetXAPI', 'getxapi.com'),
    ('HackerNews', ''),
    ('Hashnode', 'hashnode.com'),
    ('Lanyard', ''),
    ('Meetup.com', 'meetup.com'),
    ('Open Collective', 'docs.opencollective.com'),
    ('Revolt', 'developers.revolt.chat'),
    ('TamTam', 'dev.tamtam.chat'),
    ('Telegram Bot', 'core.telegram.org'),
    ('Telegraph', 'telegra.ph'),
    ('xfetch', 'xfetch.io'),
    ('API-FOOTBALL', 'api-football.com'),
    ('ApiMedic', 'apimedic.com'),
    ('balldontlie', 'balldontlie.io'),
    ('Canadian Football League (CFL)', 'api.cfl.ca'),
    ('City Bikes', 'api.citybik.es'),
    ('Cloudbet', 'cloudbet.com'),
    ('CollegeFootballData.com', 'collegefootballdata.com'),
    ('DiscGolf', 'discgolfapi.com'),
    ('Ergast F1', 'ergast.com'),
    ('Football (Soccer) Videos', 'scorebat.com'),
    ('Football Standings', ''),
    ('JCDecaux Bike', 'developer.jcdecaux.com'),
    ('MLB Records and Stats', ''),
    ('NBA Data', ''),
    ('NHL Records and Stats', ''),
    ('Oddsmagnet', 'data.oddsmagnet.com'),
    ('OpenF1', 'openf1.org'),
    ('OpenLigaDB', 'openligadb.de'),
    ('Padel Snipe', 'padelsnipe.com'),
    ('Premier League Standings', ''),
    ('PropLine', 'prop-line.com'),
    ('RacingHub', 'racinghub.net'),
    ('Sport Data', 'sportdataapi.com'),
    ('Sport List & Data', 'developers.decathlon.com'),
    ('Sport Places', 'developers.decathlon.com'),
    ('Sport Vision', 'developers.decathlon.com'),
    ('SportScore', 'sportscore.com'),
    ('Sportmonks Cricket', 'docs.sportmonks.com'),
    ('Sportmonks Football', 'docs.sportmonks.com'),
    ('Squiggle', 'api.squiggle.com.au'),
    ('SuredBits', 'suredbits.com'),
    ('TheRundown', 'therundown.io'),
    ('TheSportsDB', 'thesportsdb.com'),
    ('TourneyRadar', ''),
    ('Wger', 'ger.de'),
    ('Bacon Ipsum', 'baconipsum.com'),
    ('Dicebear Avatars', 'avatars.dicebear.com'),
    ('DummyJSON', 'dummyjson.com'),
    ('English Random Words', ''),
    ('FakeJSON', 'fakejson.com'),
    ('FakerAPI', 'fakerapi.it'),
    ('FakeStoreAPI', 'fakestoreapi.com'),
    ('GeneradorDNI', 'api.generadordni.es'),
    ('ItsThisForThat', 'itsthisforthat.com'),
    ('Loripsum', 'loripsum.net'),
    ('Mailsac', 'mailsac.com'),
    ('Metaphorsum', 'metaphorpsum.com'),
    ('Mockaroo', 'mockaroo.com'),
    ('QuickMocker', 'quickmocker.com'),
    ('Random Data', 'random-data-api.com'),
    ('Randommer', 'randommer.io'),
    ('RandomUser', 'randomuser.me'),
    ('RoboHash', 'robohash.org'),
    ('Spanish random names', ''),
    ('Spanish random words', ''),
    ('This Person Does not Exist', 'thispersondoesnotexist.com'),
    ('Toolcarton', 'testimonialapi.toolcarton.com'),
    ('TotalShiftLeft Sandbox', 'demo.totalshiftleft.ai'),
    ('UUID Generator', 'uuidtools.com'),
    ('What The Commit', 'hatthecommit.com'),
    ('Yes No', 'yesno.wtf'),
    ('Aylien Text Analysis', 'docs.aylien.com'),
    ('Audexum', 'audexum.com'),
    ('Cloudmersive Natural Language Processing', 'cloudmersive.com'),
    ('Detect Language', 'detectlanguage.com'),
    ('ELI', 'nlp.insightera.co.th'),
    ('Google Cloud Natural', ''),
    ('GeoScore', 'geoscoreapi.com'),
    ('Hirak OCR', 'ocr.hirak.site'),
    ('Hirak Translation', 'translate.hirak.site'),
    ('Kiprio Translate', 'kiprio.com'),
    ('Lecto Translation', ''),
    ('LibreTranslate', 'libretranslate.com'),
    ('Sentiment Analysis', 'meaningcloud.com'),
    ('Aftership', 'developers.aftership.com'),
    ('Correios', 'cws.correios.com.br'),
    ('PostalPinCode', 'postalpincode.in'),
    ('Postmon', 'postmon.com.br'),
    ('PostNord', 'developer.postnord.com'),
    ('UPS', 'ups.com'),
    ('WeCanTrack', 'docs.wecantrack.com'),
    ('WhatPulse', 'developer.whatpulse.org'),
    ('WhereParcel', 'hereparcel.com'),
    ('ADS-B Exchange', 'adsbexchange.com'),
    ('airportsapi', 'airport-web.appspot.com'),
    ('AIS Hub', 'aishub.net'),
    ('Apimetro', 'apimetro.dev'),
    ('AviationAPI', 'docs.aviationapi.com'),
    ('AZ511', 'az511.com'),
    ('Bay Area Rapid Transit', 'api.bart.gov'),
    ('BC Ferries', 'bcferriesapi.ca'),
    ('BlaBlaCar', 'dev.blablacar.com'),
    ('Boston MBTA Transit', 'mbta.com'),
    ('Community Transit', ''),
    ('Compare Flight Prices', ''),
    ('CTS', 'api.cts-strasbourg.eu'),
    ('FAA N-Number Registry', 'n-number.starfile.org'),
    ('GraphHopper', 'docs.graphhopper.com'),
    ('Icelandic APIs', 'docs.apis.is'),
    ('Impala Hotel Bookings', 'docs.impala.travel'),
    ('Izi', 'api-docs.izi.travel'),
    ('Land Transport Authority DataMall, Singapore', 'datamall.lta.gov.sg'),
    ('Metro Lisboa', 'app.metrolisboa.pt'),
    ('Navitia', 'doc.navitia.io'),
    ('Open Charge Map', 'openchargemap.org'),
    ('Orizn Visa', 'visa.orizn.app'),
    ('OpenSky Network', 'opensky-network.org'),
    ('OpenVan', 'openvan.camp'),
    ('Railway Transport for France', 'digital.sncf.com'),
    ('REFUGE Restrooms', 'refugerestrooms.org'),
    ('Road511', 'road511.com'),
    ('Sabre for Developers', 'developer.sabre.com'),
    ('Schiphol Airport', 'developer.schiphol.nl'),
    ('Tankerkoenig', 'creativecommons.tankerkoenig.de'),
    ('TransitLand', 'transit.land'),
    ('Transport for Atlanta, US', 'itsmarta.com'),
    ('Transport for Auckland, New Zealand', 'dev-portal.at.govt.nz'),
    ('Transport for Belgium', 'docs.irail.be'),
    ('Transport for Berlin, Germany', ''),
    ('Transport for Bordeaux, France', 'opendata.bordeaux-metropole.fr'),
    ('Transport for Budapest, Hungary', 'bkkfutar.docs.apiary.io'),
    ('Transport for Chicago, US', 'transitchicago.com'),
    ('Transport for Czech Republic', 'chaps.cz'),
    ('Transport for Denver, US', 'rtd-denver.com'),
    ('Transport for Finland', 'digitransit.fi'),
    ('Transport for Germany', 'data.deutschebahn.com'),
    ('Transport for Grenoble, France', 'mobilites-m.fr'),
    ('Transport for Hessen, Germany', 'opendata.rmv.de'),
    ('Transport for Honolulu, US', 'hea.thebus.org'),
    ('Transport for Lisbon, Portugal', 'emel.city-platform.com'),
    ('Transport for London, England', 'api.tfl.gov.uk'),
    ('Transport for Los Angeles, US', 'developer.metro.net'),
    ('Transport for Manchester, England', 'developer.tfgm.com'),
    ('Transport for Norway', 'developer.entur.org'),
    ('Transport for Ottawa, Canada', 'octranspo.com'),
    ('Transport for Paris, France', 'data.ratp.fr'),
    ('Transport for Philadelphia, US', '3.septa.org'),
    ('Transport for Spain', 'data.renfe.com'),
    ('Transport for Switzerland', 'opentransportdata.swiss'),
    ('Transport for The Netherlands', ''),
    ('Transport for Toronto, Canada', 'myttc.ca'),
    ('Transport for UK', 'developer.transportapi.com'),
    ('Transport for United States', 'retro.umoiq.com'),
    ('transport.rest', 'transport.rest'),
    ('Tripadvisor', 'developer-tripadvisor.com'),
    ('Velib metropolis, Paris, France', 'velib-metropole.fr'),
    ('1pt', ''),
    ('CleanURI', 'cleanuri.com'),
    ('ClickMeter', 'support.clickmeter.com'),
    ('Clico', 'cli.com'),
    ('Cutt.ly', 'cutt.ly'),
    ('Drivet URL Shortener', 'iki.drivet.xyz'),
    ('Free Url Shortener', 'ulvis.net'),
    ('Git.io', 'github.blog'),
    ('GoTiny', ''),
    ('Kutt', 'docs.kutt.it'),
    ('Mgnet.me', 'mgnet.me'),
    ('owo', 'owo.vc'),
    ('Rebrandly', 'developers.rebrandly.com'),
    ('RedirHub', 'redirhub.com'),
    ('Short Link', ''),
    ('Shrtcode', 'shrtco.de'),
    ('Shrtlnk', 'shrtlnk.dev'),
    ('TinyURL', 'tinyurl.com'),
    ('UrlBae', 'urlbae.com'),
    ('Auto Body Shop Directory', 'autobodyshopnear.com'),
    ('Brazilian Vehicles and Prices', ''),
    ('CarVector', 'carvector.io'),
    ('Helipaddy sites', 'helipaddy.com'),
    ('Kelley Blue Book', 'developer.kbb.com'),
    ('Mercedes-Benz', 'developer.mercedes-benz.com'),
    ('NHTSA', 'vpic.nhtsa.dot.gov'),
    ('ProblemsByVin', 'problemsbyvin.com'),
    ('RevCarData', 'revcardata.com'),
    ('An API of Ice And Fire', 'anapioficeandfire.com'),
    ("Bob's Burgers", ''),
    ('Breaking Bad', 'breakingbadapi.com'),
    ('Breaking Bad Quotes', ''),
    ('Catalogopolis', 'api.catalogopolis.xyz'),
    ('Catch The Show', ''),
    ('Czech Television', 'ceskatelevize.cz'),
    ('Dune', ''),
    ('Final Space', 'finalspaceapi.com'),
    ('Game of Thrones Quotes', 'gameofthronesquotes.xyz'),
    ('Harry Potter Charactes', ''),
    ('Hyperserve', 'hyperserve.io'),
    ('IMDb-API', 'imdb-api.com'),
    ('IMDbOT', ''),
    ('JSON2Video', 'json2video.com'),
    ('Lucifer Quotes', ''),
    ('MCU Countdown', ''),
    ('Motivational Quotes', ''),
    ('Movie Quote', ''),
    ('Open Movie Database', 'omdbapi.com'),
    ('Owen Wilson Wow', ''),
    ('Rendobar', 'rendobar.com'),
    ('Ron Swanson Quotes', ''),
    ('Simkl', 'simkl.docs.apiary.io'),
    ('STAPI', 'stapi.co'),
    ('Stranger Things Quotes', ''),
    ('Stream', 'api.stream.cz'),
    ('Stromberg Quotes', 'stromberg-api.de'),
    ('SWAPI', 'swapi.dev'),
    ('SWAPI GraphQL', 'graphql.org'),
    ('The Lord of the Rings', 'the-one-api.dev'),
    ('The Vampire Diaries', ''),
    ('ThronesApi', 'thronesapi.com'),
    ('TMDb', 'themoviedb.org'),
    ('TrailerAddict', 'traileraddict.com'),
    ('Trakt', 'trakt.docs.apiary.io'),
    ('TVDB', 'thetvdb.com'),
    ('TVMaze', 'tvmaze.com'),
    ('uNoGS', ''),
    ('Watchmode', 'api.watchmode.com'),
    ('Web Series Quotes Generator', ''),
    ('Weatherstack', 'eatherstack.com'),
    ('7Timer!', '7timer.info'),
    ('AccuWeather', 'developer.accuweather.com'),
    ('Aemet', 'opendata.aemet.es'),
    ('APIXU', 'apixu.com'),
    ('AQICN', 'aqicn.org'),
    ('AviationWeather', 'aviationweather.gov'),
    ('ColorfulClouds', 'open.caiyunapp.com'),
    ('Euskalmet', 'opendata.euskadi.eus'),
    ('HG Weather', 'hgbrasil.com'),
    ('Hong Kong Obervatory', 'hko.gov.hk'),
    ('IPMA', 'api.ipma.pt'),
    ('Micro Weather', 'm3o.com'),
    ('ODWeather', 'api.oceandrivers.com'),
    ('Oikolab', 'docs.oikolab.com'),
    ('Open-Meteo', 'open-meteo.com'),
    ('openSenseMap', 'api.opensensemap.org'),
    ('OpenUV', 'openuv.io'),
    ('OpenWeatherMap', 'openweathermap.org'),
    ('Pirate Weather', 'pirateweather.net'),
    ('QWeather', 'dev.qweather.com'),
    ('Rainbow Weather', 'developer.rainbow.ai'),
    ('RainViewer', 'rainviewer.com'),
    ('Storm Glass', 'stormglass.io'),
    ('Tomorrow', 'docs.tomorrow.io'),
    ('US Weather', 'eather.gov'),
    ('Visual Crossing', 'visualcrossing.com'),
    ('weather-api', ''),
    ('WeatherAPI', 'eatherapi.com'),
    ('Weatherbit', 'eatherbit.io'),
    ('wttr.in', 'ttr.in'),
    ('Yandex.Weather', 'yandex.com'),
)
