"""Competitor query generation — invented-name filter.

The solution name is generated by the pipeline, so it has ZERO web presence: any search
query containing it returns nothing useful and makes real competitors look absent
(live-caught 2026-07-10 — the task YAML even said "use for competitor searches").
The prompt now forbids it; the deterministic post-filter enforces it.
"""

import json
from unittest.mock import patch

from nicheiq.utils.generation.competitor_query_generator import CompetitorQueryGenerator


def _fake_response(queries):
    return json.dumps([{"query": q, "type": "category", "rationale": "r"} for q in queries])


def _generate(queries, name="BrokerPay Shield (Broker Risk + Bond Claims)"):
    with patch(
        "nicheiq.utils.generation.competitor_query_generator.LLMService.invoke_plain",
        return_value=(_fake_response(queries), None),
    ):
        gen = CompetitorQueryGenerator()
        return gen.generate_competitor_queries(
            solution_name=name, project_type="saas", num_queries=len(queries)
        )


class TestInventedNameFilter:
    def test_query_with_invented_name_dropped(self):
        out = _generate([
            "BrokerPay Shield alternatives",
            "freight broker credit check tools",
        ])
        texts = [q["query"] for q in out]
        assert "freight broker credit check tools" in texts
        assert all("brokerpay" not in t.lower() for t in texts)

    def test_name_head_matches_despite_subtitle_tail(self):
        # Name carries a "(...)" subtitle; the filter matches on the head only.
        out = _generate(["brokerpay shield (broker risk) vs competitors", "top 5 factoring tools 2026"])
        texts = [q["query"] for q in out]
        assert texts == ["top 5 factoring tools 2026"]

    def test_clean_queries_untouched(self):
        queries = ["alternatives to Truckstop for broker vetting", "DAT vs Truckstop credit data"]
        out = _generate(queries)
        assert [q["query"] for q in out] == queries

    def test_short_name_head_does_not_overfilter(self):
        # A <4-char head must not filter common words out of every query.
        out = _generate(["best crm for dispatchers"], name="Api: Load Board Helper")
        assert [q["query"] for q in out] == ["best crm for dispatchers"]
