"""Competitor query generation — invented-name filter.

The solution name is generated by the pipeline, so it has ZERO web presence: any search
query containing it returns nothing useful and makes real competitors look absent
(live-caught 2026-07-10 — the task YAML even said "use for competitor searches").
The prompt now forbids it; the deterministic post-filter enforces it.
"""

import json
from unittest.mock import patch

from nicheiq.models.research_state import NicheContext
from nicheiq.utils.generation.competitor_query_generator import CompetitorQueryGenerator


def _fake_response(queries):
    return json.dumps([{"query": q, "type": "category", "rationale": "r"} for q in queries])


def _generate(queries, name="BrokerPay Shield (Broker Risk + Bond Claims)"):
    with patch(
        "nicheiq.utils.generation.competitor_query_generator.LLMService.invoke_plain",
        return_value=(_fake_response(queries), None),
    ):
        gen = CompetitorQueryGenerator()
        return gen.generate_competitor_queries(
            solution_name=name, project_type="saas", num_queries=len(queries)
        )


class TestInventedNameFilter:
    def test_query_with_invented_name_dropped(self):
        out = _generate([
            "BrokerPay Shield alternatives",
            "freight broker credit check tools",
        ])
        texts = [q["query"] for q in out]
        assert "freight broker credit check tools" in texts
        assert all("brokerpay" not in t.lower() for t in texts)

    def test_name_head_matches_despite_subtitle_tail(self):
        # Name carries a "(...)" subtitle; the filter matches on the head only.
        out = _generate(["brokerpay shield (broker risk) vs competitors", "top 5 factoring tools 2026"])
        texts = [q["query"] for q in out]
        assert texts == ["top 5 factoring tools 2026"]

    def test_clean_queries_untouched(self):
        queries = ["alternatives to Truckstop for broker vetting", "DAT vs Truckstop credit data"]
        out = _generate(queries)
        assert [q["query"] for q in out] == queries

    def test_short_name_head_does_not_overfilter(self):
        # A <4-char head must not filter common words out of every query.
        out = _generate(["best crm for dispatchers"], name="Api: Load Board Helper")
        assert [q["query"] for q in out] == ["best crm for dispatchers"]


# --- Niche anchoring -------------------------------------------------------------------
# The solution name is invented and can carry a word that belongs to another industry
# ("HouseNut" is a live-music venue's fixed operating cost, not household budgeting).
# The competitor prompt now carries the same anchor block the Reddit/HN query generators
# get, and off-niche queries are dropped in code (live-caught 2026-08-03, run 8ef396eb).

LIVE_MUSIC_CTX = NicheContext(
    niche_input="Independent live music venues coordinating artist settlements",
    niche_description="Independent live music venue management.",
    market_segments=["Independent venue owners"],
    industry_boundaries="Operational management of physical performance spaces.",
    anchor_entities=["Prism.fm", "VenuePilot", "Eventbrite Music", "DICE"],
    disambiguation_exclusions=["Music-streaming royalty accounting"],
    audience_jargon=["artist settlement", "house nut"],
)


def _generate_with_ctx(queries, ctx, name="HouseNutIndex"):
    captured = {}

    def _fake_invoke(prompt, **kwargs):
        captured["prompt"] = prompt
        return (_fake_response(queries), None)

    with patch(
        "nicheiq.utils.generation.competitor_query_generator.LLMService.invoke_plain",
        side_effect=_fake_invoke,
    ):
        out = CompetitorQueryGenerator().generate_competitor_queries(
            solution_name=name, project_type="saas", niche_context=ctx,
            num_queries=len(queries),
        )
    return out, captured.get("prompt", "")


class TestNicheAnchoring:
    def test_anchor_entities_and_exclusions_reach_the_prompt(self):
        _, prompt = _generate_with_ctx(["Prism.fm alternatives"], LIVE_MUSIC_CTX)
        assert "ANCHOR ENTITIES" in prompt
        assert "Prism.fm" in prompt
        assert "OUT-OF-SCOPE — DO NOT TARGET" in prompt
        assert "Music-streaming royalty accounting" in prompt

    def test_prompt_pins_the_vertical_to_the_niche_not_the_name(self):
        _, prompt = _generate_with_ctx(["Prism.fm alternatives"], LIVE_MUSIC_CTX)
        assert "VERTICAL IS ALREADY FIXED" in prompt

    def test_query_matching_an_excluded_sense_is_dropped(self):
        out, _ = _generate_with_ctx(
            [
                "Prism.fm alternatives for independent venues",
                "best music-streaming royalty accounting software 2026",
            ],
            LIVE_MUSIC_CTX,
        )
        texts = [q["query"] for q in out]
        assert texts == ["Prism.fm alternatives for independent venues"]

    def test_no_anchor_block_without_niche_context(self):
        _, prompt = _generate_with_ctx(["freight broker credit check tools"], None)
        assert "ANCHOR ENTITIES" not in prompt
