/**
 * A `validate_idea` run can end `outcome: 'not_evaluated'` — the pipeline refused to grade
 * the user's idea, for one of six typed causes, ALL of which are ours. The job page is the
 * surface that told the user otherwise for four rounds: every sentence that branched on "is
 * this a validate run" or "is there an idea_validation block" asserted a grading that never
 * happened, because the block is emitted on a refusal too.
 *
 * Round 4 fixed nine of those sentences and shipped them with no render test — "no harness
 * exists for this route", which was false: the four files beside this one already render
 * `+page.svelte`. A critic copied that scaffold, reproduced the refused page in one attempt,
 * and found a TENTH surface in one extra click: the guided tour, whose "Show me around
 * again" control still sat on the refused page and replayed "run it again in your own
 * words" — the exact sentence the verdict card had been fixed to stop saying.
 *
 * So this file drives the page rather than reading it. It runs the real `+page.server.ts`
 * load against a realistic refused `/solutions` response, renders the real page component,
 * and asserts on rendered DOM — including the DOM that only exists after a click, because
 * the workbench header mounts behind a disclosure and a header assertion made without
 * expanding it passes against unfixed code.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, cleanup, waitFor, fireEvent } from "@testing-library/svelte";
import { page } from "$app/state";
import type { Job } from "$lib/types/job";

const mocks = vi.hoisted(() => ({
  fetchBackend: vi.fn(),
  // A terminal stop does not go through the solutions fetch, so the page reads the
  // idea-check block from this endpoint instead; the default null is what every
  // non-stopped test wants.
  getPreviewReport: vi.fn(() => Promise.resolve(null as unknown)),
}));

vi.mock("$lib/backend", () => ({
  fetchBackend: mocks.fetchBackend,
}));

vi.mock("$lib/api", async (importOriginal) => {
  const actual = await importOriginal<typeof import("$lib/api")>();
  return {
    ...actual,
    subscribeToProgress: vi.fn(() => () => {}),
    shouldKeepSSEOpen: vi.fn(() => false),
    getReportSummary: vi.fn(() => Promise.resolve(null)),
    getDiscoveryShareStatus: vi.fn(() =>
      Promise.resolve({ isShared: false, solutionVotes: {} })),
    getSolutions: vi.fn(() => Promise.resolve({ solutionIdeas: [] })),
    getDiscoveryData: vi.fn(() => Promise.resolve(null)),
    getPreviewReport: mocks.getPreviewReport,
    getChatHistory: vi.fn(() => Promise.resolve({ messages: [], weakPool: false })),
  };
});

import { load } from "../+page.server";
import PageComponent from "../+page.svelte";
import { TOUR_CHAPTERS } from "$lib/tour/chapters";
import { gradedBlock, notEvaluatedBlock } from "$lib/components/__tests__/fixtures/ideaValidationBlocks";

/** The tour's opening line, read from the chapter rather than copied: it is the sentence
 *  that must never reach a refused run, and a literal here would let the chapter drift. */
const TOUR_STEP_1 = (() => {
  const text = TOUR_CHAPTERS["validate-report"].steps[0]?.popover?.description;
  // Not `?? ""`: an empty needle makes `toContain` vacuously true in both directions.
  if (!text) throw new Error("validate-report chapter has no opening step to assert on");
  return text;
})();
const TOUR_RESTART_LABEL = "Show me around again";

const IDEAS = [
  {
    solution_name: "Alpha Idea",
    idea_id: "idea-alpha",
    idea_revision: 1,
    description: "Reconciles service records against the parts actually shipped",
    value_proposition: "Cuts the reconciliation pass from a day to an hour",
    market_fit_score: 0.72,
    technical_feasibility_score: 0.68,
    adjusted_composite_score: 0.71,
  },
  {
    solution_name: "Beta Idea",
    idea_id: "idea-beta",
    idea_revision: 1,
    description: "Tracks warranty claims through their approval chain",
    value_proposition: "Shows where a claim stalled without opening the portal",
    market_fit_score: 0.61,
    technical_feasibility_score: 0.64,
    adjusted_composite_score: 0.62,
  },
  {
    solution_name: "Gamma Idea",
    idea_id: "idea-gamma",
    idea_revision: 1,
    description: "Flags invoices whose line items never left the warehouse",
    value_proposition: "Catches the mismatch before the client does",
    market_fit_score: 0.58,
    technical_feasibility_score: 0.6,
    adjusted_composite_score: 0.59,
  },
];

/**
 * The block a refused run actually emits — GENERATED by `build_idea_validation_block`, not
 * written here.
 *
 * IT USED TO BE WRITTEN HERE, and that is why three rounds of assertions over this page
 * proved nothing about two of its cards. The hand-authored version carried
 * `experiment_ladder: []` and a single desk limit. The pipeline CANNOT emit that: both
 * fields (and `next_experiment_index`) are stamped on every block BEFORE the `seed is None`
 * refusal branch, which reset neither — so a real refusal shipped all four rungs with rung
 * 1 flagged as the recommended next action, under a heading promising the "lowest-cost next
 * test", on an idea the run had just declined to grade. Every assertion below rendered an
 * empty `<ol>` instead and passed vacuously.
 *
 * The fixture is now vendored from the real builder and a Python test fails the moment the
 * two disagree (tests/unit/report/test_not_evaluated_fixture_contract.py). Only the run's
 * narrative is overridden here; `headline` and `failure_next_step` come straight from
 * SEED_FAILURE_COPY through the builder, so they can no longer be transcribed wrong either.
 */
const NOT_EVALUATED_IV = notEvaluatedBlock({
  user_idea_text:
    "A tool that reconciles vet clinic invoices against the parts actually shipped, for "
    + "practice managers.",
  user_idea_brief: "Reconciles vet invoices against shipped parts.",
  derived_market: null,
  derived_buyer: null,
  // Derived, not typed: only the pool count and its top entries are this test's narrative.
  alternatives: {
    ...notEvaluatedBlock().alternatives,
    count: 3,
    named_buyer_count: null,
    top: IDEAS.map((i) => ({ idea_id: null, name: i.solution_name, one_liner: "" })),
  },
}) as unknown as Record<string, unknown>;

/**
 * The same run, graded. Used only to prove the fixes below withhold the refused wording
 * rather than deleting the feature for everyone.
 *
 * BUILT FROM THE GRADED FIXTURE, not by spreading the refused one (2026-08-15). It used to
 * be `{ ...NOT_EVALUATED_IV, outcome: "worth_testing", parts: [one part] }` — which carried
 * the REFUSAL's empty `desk_limits`, `experiment_ladder`, `competitors`, `anchored_pains`
 * and `kill_risks`, and a one-entry `parts`, into a block claiming to be graded. The
 * pipeline cannot emit that: a graded block has three parts, three desk limits, four rungs.
 * Trap 1 again, in the file trap 1 came from, on six more fields — found by deriving the
 * hand-authoring ban from the generated fixtures instead of naming two fields.
 */
const GRADED_IV = gradedBlock({
  outcome: "worth_testing",
  idea_name: "Vet Invoice Reconciler",
  headline: "The problem is real and no one ships this for your buyer yet.",
  user_idea_text: NOT_EVALUATED_IV.user_idea_text as string,
  user_idea_brief: NOT_EVALUATED_IV.user_idea_brief as string,
  alternatives: NOT_EVALUATED_IV.alternatives as never,
  seed_purchasable: true,
}) as unknown as Record<string, unknown>;

function response(body: unknown, status = 200): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => body,
  } as Response;
}

function event() {
  return {
    params: { jobId: "job-1" },
    locals: {
      auth: vi.fn().mockResolvedValue({ user: { id: "user-1", email: "owner@example.com" } }),
    },
  } as never;
}

/** The shape GET /api/jobs/:jobId/solutions returns for a verified pool
 *  (backend/src/routes/jobs.ts): `previewReport` is present only when
 *  `artifactVerification === 'verified'`, and it carries the idea-check block. */
function verifiedSolutionsResponse(
  ideaValidation: unknown,
  overrides: Record<string, unknown> = {},
) {
  return {
    solutionIdeas: IDEAS,
    selectedSolution: null,
    selectedSolutions: null,
    selectedSolutionIds: null,
    selectedSolutionRefs: null,
    selectionRationale: null,
    selectionDecisionProfile: null,
    selectionDecisionProfileVersion: null,
    selectionDraft: { version: 1, items: [], selectionFingerprint: null },
    canRegenerate: true,
    ideaBatchCompletedCount: 0,
    maxIdeaBatches: 3,
    activeOperation: null,
    status: "AWAITING_SELECTION",
    candidatePoolVersion: 4,
    artifactVerification: "verified",
    artifactReason: null,
    previewReport: {
      niche: "vet clinics",
      generated_at: "2026-08-01T00:00:00.000Z",
      idea_validation: ideaValidation,
    },
    ...overrides,
  };
}

function backendJob(status: string) {
  return {
    id: "job-1",
    niche: "vet clinics",
    status,
    entryMode: "validate_idea",
    solutionIdeas: IDEAS,
    selectedSolutions: [],
    assets: [],
    stagesCompleted: 5,
    totalStages: 16,
  } as unknown as Job;
}

async function loadPageData(
  solutionsBody: unknown,
  status = "AWAITING_SELECTION",
  previewReport: unknown = null,
) {
  mocks.fetchBackend.mockImplementation((path: string) => {
    if (path === "/api/jobs/job-1") return Promise.resolve(response(backendJob(status)));
    if (path === "/api/jobs/job-1/solutions") return Promise.resolve(response(solutionsBody));
    // A terminal stop takes the artifact path instead of the selection snapshot.
    if (path === "/api/jobs/job-1/preview-report" && previewReport) {
      return Promise.resolve(response(previewReport));
    }
    return Promise.resolve(response({}, 404));
  });
  const data = await load(event()) as Record<string, unknown>;
  return {
    ...data,
    creditBalance: 100,
    stageCosts: {
      discovery: 5, deep_research: 15, landing_page: 5, regenerate_ideas: 2, seed_idea: 3,
    },
  } as Record<string, unknown>;
}

/** Renders the page for a refused (or graded) run and waits for the verdict to land. */
async function renderRun(ideaValidation: unknown, status = "AWAITING_SELECTION") {
  const data = await loadPageData(
    verifiedSolutionsResponse(ideaValidation, status === "AWAITING_SELECTION"
      ? {}
      : { status }),
    status,
    { niche: "vet clinics", generated_at: "2026-08-01T00:00:00.000Z",
      idea_validation: ideaValidation },
  );
  const view = render(PageComponent, { props: { data: data as never } });
  return { data, view };
}

/** Markup wraps these sentences across source lines, so every text assertion below reads
 *  the DOM with runs of whitespace collapsed — otherwise a re-indent breaks the pin. */
const squash = (s: string | null | undefined) => (s ?? "").replace(/\s+/g, " ");

function setGrant(decisionTools: boolean) {
  const state = page as unknown as { data: Record<string, unknown> };
  state.data = { ...state.data, featureAccess: { decisionTools } };
}

beforeEach(() => {
  vi.clearAllMocks();
  mocks.getPreviewReport.mockImplementation(() => Promise.resolve(null as unknown));
  (Element.prototype as unknown as { scrollIntoView: () => void }).scrollIntoView = () => {};
  (window as unknown as { matchMedia: (q: string) => unknown }).matchMedia = (q: string) => ({
    matches: q.includes("min-width"), media: q, onchange: null,
    addEventListener: () => {}, removeEventListener: () => {},
    addListener: () => {}, removeListener: () => {}, dispatchEvent: () => false,
  });
  const state = page as unknown as {
    params: Record<string, string>;
    data: Record<string, unknown>;
  };
  state.params = { jobId: "job-1" };
  // The workbench's decision-guide block (and the tour itself) exist only for a
  // decision-tools grant, which reaches the page through `page.data.featureAccess`.
  state.data = {
    ...state.data,
    featureAccess: { decisionTools: true },
    creditBalance: 100,
    stageCosts: {
      discovery: 5, deep_research: 15, landing_page: 5, regenerate_ideas: 2, seed_idea: 3,
    },
  };
});

afterEach(() => {
  cleanup();
  // driver.js portals its overlay to <body>; a tour left running would leak into the
  // next test's `document.body` assertions.
  document.body.innerHTML = "";
});

describe("job page — a run that refused to grade the idea", () => {
  it("states the refusal, and claims a grading nowhere on the page", async () => {
    const { data, view } = await renderRun(NOT_EVALUATED_IV);
    expect((data.job as Record<string, unknown>).entryMode).toBe("validate_idea");
    expect(((data.previewReport as Record<string, unknown>).idea_validation as
      Record<string, unknown>).outcome).toBe("not_evaluated");

    await waitFor(() => expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));
    const text = squash(view.container.textContent);

    // Page subtitle: points at the verdict card instead of restating its cause.
    expect(text).toContain(
      "This run couldn't grade your idea. The reason, and what to do next, are below.");
    expect(text).not.toContain(
      "Your idea, developed into a product concept and checked against this market's evidence.");

    // The per-cause pair reaches the DOM verbatim from SEED_FAILURE_COPY — no second copy
    // of the decision lives in Svelte.
    expect(text).toContain(NOT_EVALUATED_IV.headline);
    expect(text).toContain(NOT_EVALUATED_IV.failure_next_step);

    // The alternatives disclosure: title, subtitle, body and the section's own aria-label.
    expect(text).toContain("The approaches this run generated");
    expect(text).toContain("3 approaches from this market's evidence. None of them is your idea.");
    expect(text).toContain("it never graded your idea against them");
    expect(text).not.toContain("How your idea was graded");
    expect(text).not.toContain("That pool is the benchmark your idea was ranked");
    expect(view.container.querySelector("#validate-alternatives")?.getAttribute("aria-label"))
      .toBe("The approaches this run generated");

    // The Overview scope line. It renders whether or not the section is expanded, so the
    // only reason a revert of it stayed green was that nothing here read it: "your idea's
    // own VERDICT is above" names a result the run refused to produce.
    expect(text).toContain(
      "This section grades the market your idea sits in, not your idea. "
      + "Your idea's own result is above.");
    expect(text).not.toContain("Your idea's own verdict is above.");

    // R6: the two findings-shaped cards, asserted HERE and not only against the component,
    // because the question this file exists to answer is what the WHOLE PAGE says. With the
    // corrected fixture and the cards restored, every other assertion in this file stays
    // green — nothing above ever read them, which is precisely how a four-rung testing plan
    // for an ungraded idea survived three rounds of this suite.
    expect(text).not.toContain("Lowest-cost next test");
    expect(text).not.toContain("Run 5 problem interviews with the buyer you named");
    expect(text).not.toContain("What this check cannot see");
    expect(view.container.querySelector(".iv-ladder")).toBeNull();

    // The R3 defect and its ancestors: a verdict on a product that was never built.
    expect(text).not.toContain("ruled out");
    expect(text).not.toContain("Run it again, or rephrase it in your own words");

    // The sidebar names the journey step. It was derived from the ENTRY MODE alone, so it
    // read "Your verdict" beside a card reading "Not evaluated".
    expect(text).not.toContain("Your verdict");
    expect(text).toContain("Idea check");
  });

  it("keeps the graded wording out of the workbench header behind the disclosure", async () => {
    const { view } = await renderRun(NOT_EVALUATED_IV);
    await waitFor(() => expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));

    // The header is NOT in the DOM yet — asserting on it now is vacuous, which is how the
    // first version of this test passed against unfixed code.
    expect(squash(view.container.querySelector("#validate-alternatives-content")?.textContent))
      .not.toContain("Add any of these to the Deep Research scope.");

    const toggle = view.container.querySelector("#validate-alternatives button") as HTMLElement;
    expect(toggle).toBeTruthy();
    await fireEvent.click(toggle);
    await waitFor(() =>
      expect(squash(view.container.querySelector("#validate-alternatives-content")?.textContent))
        .toContain("isn't in this list"));

    const opened = squash(view.container.querySelector("#validate-alternatives-content")?.textContent);
    // Absence of the seed row has two causes; only the outcome separates "demoted" from
    // "never built", and the old copy reported both as RULED OUT.
    expect(opened).toContain(
      "Your idea isn't in this list: this run couldn't grade it, so no version of it was built.");
    expect(opened).not.toContain("ruled out");
    expect(opened).not.toContain("pinned at the top for comparison");
    // The workbench's own header title. Asserting it by accessible NAME is vacuous here —
    // the sr-only <h2> above renders the same string, so a name query still finds a
    // heading with the title reverted. Read the header element itself, and pin the
    // reverted wording by absence: "Your idea, ranked with the alternatives" printed
    // directly under "Your idea isn't in this list".
    expect(squash(view.container
      .querySelector("#validate-alternatives-content .cmd-title")?.textContent))
      .toBe("The approaches this run generated");
    expect(opened).not.toContain("Your idea, ranked with the alternatives");
    // The expanded heading (sr-only h2) follows the outcome too.
    expect(squash(view.container.textContent)).not.toContain("How your idea was graded");
    expect(squash(view.container.textContent)).not.toContain("ruled out");
  });

  /**
   * A REFUSED run that also carries the user's own idea, seeded from chat.
   *
   * `POST /api/jobs/:jobId/seed` has no `entryMode` check, so a user whose check refused
   * can pay again at AWAITING_SELECTION to seed the same pitch from chat.
   * `worker/tasks.py::run_seed_idea` appends it with `source_frame: "user_seed"` and
   * `generation_operation_id: "seed_idea_N"`. The report block still says
   * `not_evaluated` — correctly, the submitted-for-checking idea was never graded — and
   * `_find_marked` still returns null, because it keys on the `validate` operation id.
   *
   * Two consumers read that as "nothing of theirs is anywhere on this run" and both were
   * wrong. `_alternatives` counted the chat seed as one of the market's approaches (fixed
   * in Python: it now excludes every `user_seed`, and the refused block for this pool is
   * byte-identical to one without it). This list still renders it — correctly, it is a
   * selectable candidate — so the header's claim is what has to change here.
   */
  const CHAT_SEEDED_IDEA = {
    solution_name: "My Own Pitch",
    idea_id: "idea-chat-seed",
    idea_revision: 1,
    description: "Reconciles vet clinic invoices against the parts actually shipped",
    value_proposition: "The user's own idea, seeded from chat after the refusal",
    market_fit_score: 0.55,
    technical_feasibility_score: 0.57,
    adjusted_composite_score: 0.56,
    source_frame: "user_seed",
    generation_operation_id: "seed_idea_1",
  };

  /** The pool the user actually sees: this run's approaches, plus their own chat seed. */
  const POOL_WITH_CHAT_SEED = [...IDEAS, CHAT_SEEDED_IDEA];

  async function renderWithChatSeed() {
    const data = await loadPageData(
      verifiedSolutionsResponse(NOT_EVALUATED_IV, { solutionIdeas: POOL_WITH_CHAT_SEED }),
      "AWAITING_SELECTION",
      { niche: "vet clinics", generated_at: "2026-08-01T00:00:00.000Z",
        idea_validation: NOT_EVALUATED_IV },
    );
    return render(PageComponent, { props: { data: data as never } });
  }

  it("does not tell a user with a chat-seeded idea that nothing of theirs is in the list",
    async () => {
      const view = await renderWithChatSeed();
      await waitFor(() =>
        expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));

      const toggle = view.container.querySelector("#validate-alternatives button") as HTMLElement;
      await fireEvent.click(toggle);
      await waitFor(() =>
        expect(squash(view.container.querySelector("#validate-alternatives-content")?.textContent))
          .toContain("isn't in this list"));
      const opened = squash(
        view.container.querySelector("#validate-alternatives-content")?.textContent);

      // The row IS rendered — the premise of the whole assertion, pinned so this cannot
      // pass by the list quietly dropping it.
      expect(view.container.querySelector('[data-idea-id="idea-chat-seed"]')).toBeTruthy();

      // …so the unqualified claim is false and must not be on the page.
      expect(opened).not.toContain(
        "Your idea isn't in this list: this run couldn't grade it, so no version of it was built.");
      expect(opened).toContain(
        "The idea you submitted for checking isn't in this list: this run couldn't grade "
        + "it, so no version of it was built. The idea you seeded from chat is in the list "
        + "— that one was graded.");
      // The refusal is still the verdict on the submitted idea; nothing here upgrades it.
      expect(opened).not.toContain("ruled out");
      expect(opened).not.toContain("pinned at the top for comparison");
    });

  it("keeps the unqualified wording when the user has no idea of their own in the list",
    async () => {
      // The control. Without it, hard-coding the chat-seed sentence would also pass.
      const { view } = await renderRun(NOT_EVALUATED_IV);
      await waitFor(() =>
        expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));
      const toggle = view.container.querySelector("#validate-alternatives button") as HTMLElement;
      await fireEvent.click(toggle);
      await waitFor(() =>
        expect(squash(view.container.querySelector("#validate-alternatives-content")?.textContent))
          .toContain("isn't in this list"));
      const opened = squash(
        view.container.querySelector("#validate-alternatives-content")?.textContent);

      expect(view.container.querySelector('[data-idea-id="idea-chat-seed"]')).toBeNull();
      expect(opened).toContain(
        "Your idea isn't in this list: this run couldn't grade it, so no version of it was built.");
      expect(opened).not.toContain("The idea you seeded from chat");
    });

  it("counts the market's approaches without the user's own, and the list agrees",
    async () => {
      /* The seam. The collapsed disclosure prints `alternatives.count`; the list below is
       * `displaySolutions`, a different path (GET /solutions -> the candidate pool). They
       * are not the same set and never were — a graded run pins the seed in the list and
       * excludes it from the count, which is why the copy says "OTHER approaches". What
       * has to hold is the sentence's own claim: the counted approaches are the market's,
       * "None of them is your idea". So the number must be the rendered rows MINUS the
       * user's own, and the rule is stated here rather than pinned as a literal. */
      const view = await renderWithChatSeed();
      await waitFor(() =>
        expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));

      const marketApproaches = POOL_WITH_CHAT_SEED.filter(
        (s) => (s as { source_frame?: string }).source_frame !== "user_seed");
      expect(marketApproaches).toHaveLength(3);
      expect(squash(view.container.textContent)).toContain(
        `${marketApproaches.length} approaches from this market's evidence. `
        + "None of them is your idea.");

      const toggle = view.container.querySelector("#validate-alternatives button") as HTMLElement;
      await fireEvent.click(toggle);
      await waitFor(() =>
        expect(view.container.querySelector('[data-idea-id="idea-chat-seed"]')).toBeTruthy());

      // The list carries every candidate, the user's own included — one more row than the
      // sentence counts, and that difference is exactly the user's own idea.
      const rendered = [...view.container.querySelectorAll("[data-idea-id]")]
        .map((el) => el.getAttribute("data-idea-id"));
      expect(rendered).toHaveLength(POOL_WITH_CHAT_SEED.length);
      expect(rendered.length - marketApproaches.length).toBe(1);
    });

  it("does not tell a stopped refused run that its idea's check is intact", async () => {
    const { view } = await renderRun(NOT_EVALUATED_IV, "FAILED");
    await waitFor(() => expect(squash(view.container.textContent)).toContain("This run's market work"));
    const text = squash(view.container.textContent);
    expect(text).toContain("Your idea itself was not graded on this run.");
    expect(text).not.toContain("Your idea's check is intact.");
    expect(text).not.toContain("it was graded");
  });
});

/**
 * The in-run progress screen. It reads no report data at all — it takes `entryMode` and
 * nothing else — so no sweep keyed on consumers of `idea_validation` could reach it, and
 * every idea-check sentence on it was written for a run that WAS graded. The route into
 * it is the refusal sentence on /selection/review ("…so there is no version of it to
 * research. Deep Research will cover X"): the user clicks through that and lands here.
 */
describe("job page — the in-run progress screen on a refused run", () => {
  type View = { container: HTMLElement };
  const progress = (view: View) =>
    view.container.querySelector(".research-progress") as HTMLElement | null;
  const segments = (view: View) =>
    Array.from(view.container.querySelectorAll(".rp-seg")).map((seg) => ({
      label: squash(seg.querySelector(".rp-seg-label")?.textContent),
      state: seg.getAttribute("data-state"),
    }));

  it("shows no completed verdict step, and promises no spec, while Deep Research runs",
    async () => {
      const { view } = await renderRun(NOT_EVALUATED_IV, "RUNNING_PHASE2");
      await waitFor(() => expect(progress(view)).toBeTruthy());
      const text = squash(progress(view)!.textContent);

      // The track marked phase 2 DONE on a run that refused to produce a verdict. It is
      // dropped rather than relabelled: every segment before the active one fills, so a
      // kept segment would be a bar that can never complete.
      expect(segments(view)).toEqual([
        { label: "Research", state: "done" },
        { label: "Deep Research", state: "active" },
      ]);
      expect(text).not.toContain("Your verdict");

      // Present tense, on work that had already stopped.
      expect(text).not.toContain("Checking your idea against this market");
      expect(text).toContain("This run couldn't grade your idea");

      // The spec-and-score promise: neither was written, and neither will be.
      expect(text).not.toContain("write your pitch up as a complete product spec");
      expect(text).toContain(
        "Your pitch was not written up as a product spec or scored on this run.");

      // Chrome, not the failure story. The six typed causes have exactly one home
      // (SEED_FAILURE_COPY); a second copy here is what this ledger exists to prevent.
      expect(text).not.toContain(NOT_EVALUATED_IV.headline);
      expect(text).not.toContain(NOT_EVALUATED_IV.failure_next_step);
    });

  it("leaves a GRADED run's progress chrome exactly as it was", async () => {
    const { view } = await renderRun(GRADED_IV, "RUNNING_PHASE2");
    await waitFor(() => expect(progress(view)).toBeTruthy());
    const text = squash(progress(view)!.textContent);

    expect(segments(view)).toEqual([
      { label: "Research", state: "done" },
      { label: "Your verdict", state: "done" },
      { label: "Deep Research", state: "active" },
    ]);
    expect(text).toContain("Checking your idea against this market");
    expect(text).toContain(
      "write your pitch up as a complete product spec — name included — and score it");
    expect(text).not.toContain("couldn't grade your idea");
  });

  /**
   * THE PROPERTY, not the two states that break it. The screen used to take a BOOLEAN whose
   * `false` meant "graded", so any caller that could not READ the outcome asserted one.
   *
   * Two ways to get there, both reproduced below and both previously silent — no retry, no
   * failure marker, none of the "Idea check snapshot unavailable … Refresh check" treatment
   * the same page gives an untrusted artifact at AWAITING_SELECTION:
   *
   *   QUEUED + DEEP_RESEARCH — `GET /preview-report` 400'd for the entire queue wait, which
   *     is unbounded under load, on the screen that says "You can safely close this tab".
   *     And this is the DESIGNED destination of /selection/review's "we could not grade your
   *     idea" handoff, so the refused run is the one most likely to be standing here.
   *   RUNNING_PHASE2 + 5xx — the artifact exists and is allowed; the fetch just failed.
   *
   * The screen now takes a three-state outcome defaulting to "unknown", and states neither
   * result there: the caption drops to provenance, the method sentence is withheld, and the
   * middle segment is named for the work that certainly happened rather than for a verdict
   * that may or may not exist.
   */
  const loadWithPreviewStatus = async (
    status: string,
    previewStatus: number,
    body: unknown,
    activeDispatchKind: string | null = "DEEP_RESEARCH",
  ) => {
    mocks.fetchBackend.mockImplementation((path: string) => {
      if (path === "/api/jobs/job-1") {
        return Promise.resolve(response({ ...backendJob(status), activeDispatchKind }));
      }
      if (path === "/api/jobs/job-1/preview-report") {
        return Promise.resolve(response(body, previewStatus));
      }
      if (path === "/api/jobs/job-1/solutions") {
        return Promise.resolve(response(verifiedSolutionsResponse(null, { status })));
      }
      return Promise.resolve(response({}, 404));
    });
    const data = await load(event()) as Record<string, unknown>;
    return render(PageComponent, { props: { data: { ...data, creditBalance: 100 } as never } });
  };

  const REFUSED_PREVIEW = {
    niche: "vet clinics",
    generated_at: "2026-08-01T00:00:00.000Z",
    idea_validation: NOT_EVALUATED_IV,
  };

  it("reads the refusal through the QUEUED window before Deep Research starts", async () => {
    const view = await loadWithPreviewStatus("QUEUED", 200, REFUSED_PREVIEW);
    await waitFor(() => expect(progress(view)).toBeTruthy());
    const text = squash(progress(view)!.textContent);

    // The backend half (`isQueuedDeepResearch`, routes/jobs.ts) and this fetch are one fix:
    // without the loader change the response is never requested, without the backend change
    // it is a 400. Either alone leaves the assertions below red.
    expect(segments(view).map((s) => s.label)).toEqual(["Research", "Deep Research"]);
    expect(text).toContain("This run couldn't grade your idea");
    expect(text).not.toContain("Checking your idea against this market");
    expect(text).not.toContain("write your pitch up as a complete product spec");
  });

  it("asserts NO outcome when the artifact cannot be read (5xx)", async () => {
    const view = await loadWithPreviewStatus("RUNNING_PHASE2", 503, {});
    await waitFor(() => expect(progress(view)).toBeTruthy());
    const text = squash(progress(view)!.textContent);

    // Neither claim. The old boolean printed the graded one here.
    expect(text).not.toContain("Checking your idea against this market");
    expect(text).not.toContain("write your pitch up as a complete product spec");
    expect(text).not.toContain("This run couldn't grade your idea");
    expect(text).not.toContain("Your pitch was not written up as a product spec");
    expect(text).toContain("Started from your idea");

    // The middle segment: neither dropped (that asserts no verdict) nor "Your verdict"
    // filled and done (that asserts one).
    expect(segments(view)).toEqual([
      { label: "Research", state: "done" },
      { label: "Idea check", state: "done" },
      { label: "Deep Research", state: "active" },
    ]);
  });

  it("still promises the spec during Phase 1, where 'unknown' means 'not yet'", async () => {
    // The control for the safe default: "unknown" is the state of every discovery-phase run,
    // and withholding the method sentence there would delete it from the happy path.
    const view = await loadWithPreviewStatus("RUNNING", 404, {}, "DISCOVERY");
    await waitFor(() => expect(progress(view)).toBeTruthy());
    const text = squash(progress(view)!.textContent);

    expect(text).toContain("Checking your idea against this market");
    expect(text).toContain(
      "write your pitch up as a complete product spec — name included — and score it");
    expect(text).not.toContain("Started from your idea");
  });
});

describe("job page — the guided tour on a refused run", () => {
  it("offers no restart control, with the decision-tools grant", async () => {
    const { view } = await renderRun(NOT_EVALUATED_IV);
    await waitFor(() => expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));
    expect(view.queryByRole("button", { name: TOUR_RESTART_LABEL })).toBeNull();
    // Nothing anywhere on the page replays the chapter's opening claim.
    expect(squash(document.body.textContent)).not.toContain(TOUR_STEP_1);
  });

  it("offers no restart control without the grant either", async () => {
    setGrant(false);
    const { view } = await renderRun(NOT_EVALUATED_IV);
    await waitFor(() => expect(squash(view.container.textContent)).toContain("couldn't grade your idea"));
    expect(view.queryByRole("button", { name: TOUR_RESTART_LABEL })).toBeNull();
  });

  it("still offers, and still runs, the tour on a GRADED check", async () => {
    const { view } = await renderRun(GRADED_IV);
    await waitFor(() => expect(squash(view.container.textContent)).toContain(GRADED_IV.headline));

    const restart = await waitFor(() =>
      view.getByRole("button", { name: TOUR_RESTART_LABEL }));
    await fireEvent.click(restart);
    await waitFor(
      () => expect(squash(document.body.textContent)).toContain(TOUR_STEP_1),
      { timeout: 3000 },
    );
  });
});
