<script lang="ts">
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';
	import {
		FileText,
		ExternalLink,
		ArrowUp,
		MessageSquare,
		TrendingUp,
		Target,
		CheckCircle2,
		XCircle,
		PieChart,
		DollarSign,
		Shield,
		Users,
		Sparkles,
		BadgeCheck,
		Key,
		Link2,
		Ban
	} from 'lucide-svelte';

	interface Props {
		hasSampleReport?: boolean;
	}

	let { hasSampleReport = false }: Props = $props();

	let isVisible = $state(false);
	let activeTab = $state<'pain_points' | 'seo_keywords' | 'competitors' | 'business_intel'>('pain_points');

	onMount(() => {
		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry.isIntersecting) {
					isVisible = true;
				}
			},
			{ threshold: 0.1 }
		);

		const section = document.getElementById('sample-report');
		if (section) observer.observe(section);

		return () => observer.disconnect();
	});

	const tabs = [
		{ id: 'pain_points', label: 'Pain Points', icon: Target },
		{ id: 'seo_keywords', label: 'SEO Keywords', icon: TrendingUp },
		{ id: 'competitors', label: 'Competitors', icon: Users },
		{ id: 'business_intel', label: 'Business Intel', icon: PieChart }
	] as const;

	const samplePainPoints = [
		{
			title: 'Manual content repurposing consuming 3-5 hours daily',
			severity: 0.85,
			wtp: 0.78,
			mentions: 47,
			source: 'r/marketing/xyz789',
			upvotes: 143,
			date: 'Mar 15, 2024'
		},
		{
			title: 'Inconsistent brand voice across platforms',
			severity: 0.72,
			wtp: 0.65,
			mentions: 34,
			source: 'r/SaaS/abc123',
			upvotes: 89,
			date: 'Mar 12, 2024'
		},
		{
			title: 'Analytics scattered across 5+ tools',
			severity: 0.68,
			wtp: 0.71,
			mentions: 28,
			source: 'r/startups/def456',
			upvotes: 67,
			date: 'Mar 10, 2024'
		}
	];

	const sampleKeywords = [
		{ keyword: 'content repurposing tool', volume: 2400, difficulty: 0.42, tier: 'Quick Win' },
		{ keyword: 'ai content automation', volume: 1800, difficulty: 0.56, tier: 'High Value' },
		{ keyword: 'social media scheduler', volume: 5400, difficulty: 0.68, tier: 'Premium' },
		{ keyword: 'repurpose video content', volume: 1200, difficulty: 0.38, tier: 'Quick Win' },
		{ keyword: 'content automation software', volume: 980, difficulty: 0.51, tier: 'High Value' }
	];

	const competitorFeatures = [
		{ feature: 'Auto-Captions', opusclip: true, descript: true, yourmvp: true, gap: false },
		{ feature: 'Timeline Editor', opusclip: false, descript: true, yourmvp: false, gap: false },
		{ feature: 'Multi-Platform Export', opusclip: true, descript: true, yourmvp: true, gap: false },
		{ feature: 'AI Scene Detection', opusclip: true, descript: false, yourmvp: true, gap: false },
		{ feature: 'Contextual B-Roll', opusclip: false, descript: false, yourmvp: true, gap: true },
		{ feature: 'Brand Voice Matching', opusclip: false, descript: false, yourmvp: true, gap: true }
	];

	const keywordStats = {
		totalKeywords: 156,
		avgVolume: 2340,
		quickWins: 23,
		highValue: 18
	};
</script>

<section id="sample-report" class="section">
	<div class="max-w-6xl mx-auto px-6 lg:px-12">
		{#if isVisible}
			<!-- Section Header -->
			<div class="mb-12">
				<span class="section-label animate-fade-in">Sample Report</span>
				<h2 class="animate-fade-in delay-100 font-display text-4xl sm:text-5xl font-bold text-text-primary mt-4 mb-6">
					This Is Your <span class="text-gradient italic">Actual Report</span>
				</h2>
				<div class="w-16 h-1 bg-gradient-to-r from-accent to-accent-hover rounded-full animate-fade-in delay-200"></div>
				<p class="animate-fade-in delay-200 text-base sm:text-lg text-text-secondary mt-4 sm:mt-6 max-w-2xl">
					A real example of a Business Blueprint generated by NicheIQ.
				</p>
				<p class="animate-fade-in delay-300 text-sm sm:text-base text-text-muted mt-4 sm:mt-5 max-w-2xl">
					Below is a section from a market research report for a content repurposing idea — showing validated pain points, demand signals, and why this niche is worth building.
				</p>
			</div>

			<!-- Tab Navigation -->
			<div class="animate-fade-in delay-300 flex flex-wrap justify-center gap-2 mb-8">
				{#each tabs as tab}
					{@const Icon = tab.icon}
					<button
						onclick={() => (activeTab = tab.id)}
						class="px-4 py-2.5 rounded-lg font-body font-medium text-sm transition-all duration-200 flex items-center gap-2
						{activeTab === tab.id
							? 'bg-accent/10 text-accent border border-accent/50'
							: 'bg-bg-surface text-text-muted hover:text-text-primary border border-border hover:border-border-emphasis'}"
					>
						<Icon class="w-4 h-4" />
						{tab.label}
					</button>
				{/each}
			</div>

			<!-- Tab Content -->
			<div class="animate-fade-in delay-400 max-w-4xl mx-auto">
				{#if activeTab === 'pain_points'}
					<div in:fade={{ duration: 200 }}>
						<div class="bg-bg-elevated border border-border rounded-xl p-6 sm:p-8">
							<div class="flex items-center gap-3 mb-6 pb-4 border-b border-border">
								<div class="w-10 h-10 rounded-lg bg-accent/10 border border-accent/30 flex items-center justify-center">
									<Target class="w-5 h-5 text-accent" />
								</div>
								<div>
									<h3 class="font-display font-semibold text-text-primary">Pain Points We Found</h3>
									<p class="text-sm text-text-muted">Extracted from 89 social discussions</p>
								</div>
							</div>

							<div class="space-y-4">
								{#each samplePainPoints as point, i}
									<div class="p-4 rounded-lg bg-bg-surface border border-border">
										<div class="flex items-start justify-between gap-4 mb-3">
											<h5 class="font-medium text-text-primary">{point.title}</h5>
											<span class="badge badge-success text-xs shrink-0">#{i + 1}</span>
										</div>

										<div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-3 text-sm">
											<div>
												<span class="text-xs text-text-muted block">Severity</span>
												<span class="font-mono text-accent font-semibold">{point.severity}</span>
											</div>
											<div>
												<span class="text-xs text-text-muted block">WTP Score</span>
												<span class="font-mono text-accent-light font-semibold">{point.wtp}</span>
											</div>
											<div>
												<span class="text-xs text-text-muted block">Mentions</span>
												<span class="font-mono text-text-primary font-semibold">{point.mentions}</span>
											</div>
											<div>
												<span class="text-xs text-text-muted block">Source</span>
												<span class="text-accent text-sm flex items-center gap-1 cursor-pointer hover:underline">
													{point.source}
													<ExternalLink class="w-3 h-3" />
												</span>
											</div>
										</div>

										<div class="flex items-center gap-4 text-xs text-text-muted">
											<span class="flex items-center gap-1">
												<ArrowUp class="w-3 h-3" />
												{point.upvotes} upvotes
											</span>
											<span class="flex items-center gap-1">
												<MessageSquare class="w-3 h-3" />
												{point.date}
											</span>
										</div>
									</div>
								{/each}
							</div>

							<!-- Core Insight -->
							<div class="mt-6 p-4 rounded-lg bg-accent/5 border border-accent/20">
								<p class="text-sm text-text-secondary">
									<span class="font-semibold text-accent">Core Insight:</span> 47 mentions of time-consuming manual work with 0.78 willingness-to-pay score suggests strong demand for automation.
								</p>
							</div>
						</div>
					</div>
				{:else if activeTab === 'seo_keywords'}
					<div in:fade={{ duration: 200 }}>
						<div class="bg-bg-elevated border border-border rounded-xl p-6 sm:p-8">
							<div class="flex items-center gap-3 mb-6 pb-4 border-b border-border">
								<div class="w-10 h-10 rounded-lg bg-accent/10 border border-accent/30 flex items-center justify-center">
									<TrendingUp class="w-5 h-5 text-accent" />
								</div>
								<div>
									<h3 class="font-display font-semibold text-text-primary">SEO Keyword Opportunities</h3>
									<p class="text-sm text-text-muted">Live search data validation</p>
								</div>
							</div>

							<!-- Stats Summary -->
							<div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
								<div class="text-center p-3 rounded-lg bg-bg-surface border border-border">
									<span class="block text-2xl font-display font-bold text-accent">{keywordStats.totalKeywords}</span>
									<span class="text-xs text-text-muted">Keywords Found</span>
								</div>
								<div class="text-center p-3 rounded-lg bg-bg-surface border border-border">
									<span class="block text-2xl font-display font-bold text-text-primary">{keywordStats.avgVolume.toLocaleString()}</span>
									<span class="text-xs text-text-muted">Avg Volume</span>
								</div>
								<div class="text-center p-3 rounded-lg bg-bg-surface border border-border">
									<span class="block text-2xl font-display font-bold text-success">{keywordStats.quickWins}</span>
									<span class="text-xs text-text-muted">Quick Wins</span>
								</div>
								<div class="text-center p-3 rounded-lg bg-bg-surface border border-border">
									<span class="block text-2xl font-display font-bold text-warning">{keywordStats.highValue}</span>
									<span class="text-xs text-text-muted">High Value</span>
								</div>
							</div>

							<div class="overflow-x-auto">
								<table class="dark-table w-full text-sm">
									<thead>
										<tr>
											<th class="text-left py-3">Keyword</th>
											<th class="text-right py-3">Volume</th>
											<th class="text-right py-3">Difficulty</th>
											<th class="text-right py-3">Tier</th>
										</tr>
									</thead>
									<tbody>
										{#each sampleKeywords as kw}
											<tr>
												<td class="py-3 font-mono text-text-primary">{kw.keyword}</td>
												<td class="py-3 text-right text-text-secondary">{kw.volume.toLocaleString()}/mo</td>
												<td class="py-3 text-right">
													<span class="font-mono {kw.difficulty < 0.5 ? 'text-success' : kw.difficulty < 0.65 ? 'text-warning' : 'text-error'}">
														{kw.difficulty}
													</span>
												</td>
												<td class="py-3 text-right">
													<span class="badge {kw.tier === 'Quick Win' ? 'badge-success' : kw.tier === 'Premium' ? 'text-warning border-warning' : ''}">
														{kw.tier}
													</span>
												</td>
											</tr>
										{/each}
									</tbody>
								</table>
							</div>

							<p class="text-xs text-text-muted mt-4 text-center">
								Showing 5 of 156 validated keywords. Full report includes all tiers with content strategy.
							</p>
						</div>
					</div>
				{:else if activeTab === 'competitors'}
					<div in:fade={{ duration: 200 }}>
						<div class="bg-bg-elevated border border-border rounded-xl p-6 sm:p-8">
							<div class="flex items-center gap-3 mb-6 pb-4 border-b border-border">
								<div class="w-10 h-10 rounded-lg bg-accent/10 border border-accent/30 flex items-center justify-center">
									<Users class="w-5 h-5 text-accent" />
								</div>
								<div>
									<h3 class="font-display font-semibold text-text-primary">Competitive Analysis</h3>
									<p class="text-sm text-text-muted">Feature gaps identified in your niche</p>
								</div>
							</div>

							<!-- Feature Matrix -->
							<div class="overflow-x-auto">
								<table class="dark-table w-full text-sm">
									<thead>
										<tr>
											<th class="text-left py-3">Feature</th>
											<th class="text-center py-3">OpusClip</th>
											<th class="text-center py-3">Descript</th>
											<th class="text-center py-3">Your MVP</th>
										</tr>
									</thead>
									<tbody>
										{#each competitorFeatures as row}
											<tr class={row.gap ? 'bg-success/5' : ''}>
												<td class="py-3 text-text-primary">
													{row.feature}
													{#if row.gap}
														<span class="ml-2 text-xs px-1.5 py-0.5 rounded bg-success/20 text-success font-semibold">GAP!</span>
													{/if}
												</td>
												<td class="py-3 text-center">
													{#if row.opusclip}
														<CheckCircle2 class="w-4 h-4 text-success mx-auto" />
													{:else}
														<XCircle class="w-4 h-4 text-text-muted/50 mx-auto" />
													{/if}
												</td>
												<td class="py-3 text-center">
													{#if row.descript}
														<CheckCircle2 class="w-4 h-4 text-success mx-auto" />
													{:else}
														<XCircle class="w-4 h-4 text-text-muted/50 mx-auto" />
													{/if}
												</td>
												<td class="py-3 text-center">
													{#if row.yourmvp}
														<CheckCircle2 class="w-4 h-4 text-accent mx-auto" />
													{:else}
														<XCircle class="w-4 h-4 text-text-muted/50 mx-auto" />
													{/if}
												</td>
											</tr>
										{/each}
									</tbody>
								</table>
							</div>

							<!-- Gap Summary -->
							<div class="mt-6 p-4 rounded-lg bg-success/5 border border-success/20">
								<div class="flex items-start gap-3">
									<Sparkles class="w-5 h-5 text-success shrink-0 mt-0.5" />
									<div>
										<p class="font-semibold text-success text-sm mb-1">Market Gaps Identified</p>
										<p class="text-sm text-text-secondary">
											<strong>Contextual B-Roll</strong> and <strong>Brand Voice Matching</strong> are unserved by existing competitors. These represent differentiation opportunities with validated pain point demand.
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				{:else if activeTab === 'business_intel'}
					<div in:fade={{ duration: 200 }}>
						<div class="bg-bg-elevated border border-border rounded-xl p-6 sm:p-8">
							<div class="flex items-center gap-3 mb-6 pb-4 border-b border-border">
								<div class="w-10 h-10 rounded-lg bg-accent/10 border border-accent/30 flex items-center justify-center">
									<PieChart class="w-5 h-5 text-accent" />
								</div>
								<div>
									<h3 class="font-display font-semibold text-text-primary">Business Intelligence</h3>
									<p class="text-sm text-text-muted">Market sizing, pricing & risk assessment</p>
								</div>
							</div>

							<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
								<!-- Market Sizing -->
								<div class="p-4 rounded-lg bg-bg-surface border border-border">
									<div class="flex items-center gap-2 mb-3">
										<PieChart class="w-4 h-4 text-accent" />
										<span class="font-display font-semibold text-text-primary text-sm">Market Sizing</span>
									</div>
									<div class="space-y-2">
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">TAM</span>
											<span class="font-mono text-text-primary">$2.4B</span>
										</div>
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">SAM</span>
											<span class="font-mono text-text-primary">$340M</span>
										</div>
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">SOM (Year 1)</span>
											<span class="font-mono text-accent">$8.5M</span>
										</div>
									</div>
								</div>

								<!-- Pricing Strategy -->
								<div class="p-4 rounded-lg bg-bg-surface border border-border">
									<div class="flex items-center gap-2 mb-3">
										<DollarSign class="w-4 h-4 text-accent" />
										<span class="font-display font-semibold text-text-primary text-sm">Pricing Strategy</span>
									</div>
									<div class="space-y-2">
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">Starter</span>
											<span class="font-mono text-text-primary">$29/mo</span>
										</div>
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">Pro</span>
											<span class="font-mono text-text-primary">$79/mo</span>
										</div>
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">Business</span>
											<span class="font-mono text-accent">$199/mo</span>
										</div>
									</div>
								</div>

								<!-- Risk Assessment -->
								<div class="p-4 rounded-lg bg-bg-surface border border-success/30">
									<div class="flex items-center gap-2 mb-3">
										<Shield class="w-4 h-4 text-success" />
										<span class="font-display font-semibold text-text-primary text-sm">Risk Assessment</span>
									</div>
									<div class="space-y-2">
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">Verdict</span>
											<span class="font-mono font-bold text-success">GO</span>
										</div>
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">Confidence</span>
											<span class="font-mono text-text-primary">87%</span>
										</div>
										<div class="flex justify-between text-sm">
											<span class="text-text-muted">Risk Level</span>
											<span class="font-mono text-warning">Medium</span>
										</div>
									</div>
								</div>
							</div>

							<!-- Verdict Summary -->
							<div class="p-5 rounded-lg bg-success/5 border border-success/30">
								<div class="flex items-center gap-3 mb-3">
									<div class="w-12 h-12 rounded-full bg-success/20 border border-success/50 flex items-center justify-center">
										<CheckCircle2 class="w-6 h-6 text-success" />
									</div>
									<div>
										<p class="font-display font-bold text-success text-lg">VERDICT: GO</p>
										<p class="text-sm text-text-muted">87% confidence score</p>
									</div>
								</div>
								<p class="text-sm text-text-secondary">
									Strong pain point validation (0.85 severity), accessible market gaps, and favorable competitive landscape support moving forward with MVP development.
								</p>
							</div>
						</div>
					</div>
				{/if}

				<!-- CTA -->
				{#if hasSampleReport}
					<div class="mt-8 text-center">
						<a href="/sample-report" class="btn-secondary inline-flex items-center gap-2">
							<FileText class="w-4 h-4" />
							View Sample Report
						</a>
					</div>
				{/if}
			</div>
		{/if}
	</div>
</section>
