<script lang="ts">
	import { FileText, ArrowRight } from 'lucide-svelte';

	// This will be populated by the build process or can be managed manually
	// For now, we'll show a placeholder
	const reports: { slug: string; name: string; niche: string; date: string }[] = [];
</script>

<div class="min-h-screen bg-bg-base">
	<div class="max-w-4xl mx-auto px-6 py-16">
		<div class="text-center mb-12">
			<h1 class="text-4xl font-bold text-text-primary mb-4">
				NicheIQ <span class="text-gradient">Report Viewer</span>
			</h1>
			<p class="text-lg text-text-secondary">
				View comprehensive market research reports generated by NicheIQ
			</p>
		</div>

		{#if reports.length === 0}
			<div class="card text-center py-12">
				<FileText class="w-16 h-16 text-text-muted mx-auto mb-4" />
				<h2 class="text-xl font-semibold text-text-primary mb-2">No Reports Yet</h2>
				<p class="text-text-secondary mb-6">
					Add reports using the CLI script:
				</p>
				<code class="block bg-bg-surface p-4 rounded-lg text-sm text-accent font-mono">
					npm run add-report -- path/to/report.json
				</code>
			</div>
		{:else}
			<div class="space-y-4">
				{#each reports as report}
					<a
						href="/reports/{report.slug}"
						class="card block hover:border-accent/50 transition-colors"
					>
						<div class="flex items-center justify-between">
							<div>
								<h2 class="text-lg font-semibold text-text-primary">{report.name}</h2>
								<p class="text-sm text-text-secondary">{report.niche}</p>
								<p class="text-xs text-text-muted mt-1">{report.date}</p>
							</div>
							<ArrowRight class="w-5 h-5 text-text-muted" />
						</div>
					</a>
				{/each}
			</div>
		{/if}

		<div class="mt-12 text-center text-sm text-text-muted">
			<p>Powered by <a href="https://nicheiq.com" class="text-accent hover:text-accent-light">NicheIQ</a></p>
		</div>
	</div>
</div>
