import { describe, expect, it, vi, beforeEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const { mockGetPreviewReportForJob } = vi.hoisted(() => ({
  mockGetPreviewReportForJob: vi.fn(),
}));
vi.mock('../selectionBoundary/rawPreviewReport.js', () => ({
  getPreviewReportForJob: mockGetPreviewReportForJob,
}));

import {
  IDEA_CHECK_RECORD_FIELDS,
  loadCurrentSelectionContext,
} from '../currentSelectionContext.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..', '..', '..');

/** The REAL graded block the pipeline emits, generated by `build_idea_validation_block` and
 *  vendored for the frontend refused-page suite. Using it rather than a hand-written stand-in
 *  is the whole point: 39 of its keys are things this record must NOT carry, and a
 *  hand-written probe would only contain the ones its author thought of. */
const GENERATED_BLOCK = JSON.parse(readFileSync(
  resolve(
    REPO,
    'frontend/src/lib/components/__tests__/fixtures/ideaValidationGraded.generated.json',
  ),
  'utf8',
)) as Record<string, unknown>;

function txFor(job: Record<string, unknown>) {
  return {
    job: { findUnique: vi.fn().mockResolvedValue(job) },
    jobAsset: { findUnique: vi.fn().mockResolvedValue({ candidatePoolVersion: 7 }) },
  } as never;
}

const VALIDATE_JOB = {
  status: 'COMPLETED',
  niche: 'a pitch',
  solutionIdeas: [{ idea_id: 'a', idea_revision: 1 }],
  candidatePoolVersion: 7,
  gateStage: null,
  activeDispatchId: null,
  entryMode: 'validate_idea',
};

/**
 * F-5 — THE NARROWNESS WAS A CONVENTION.
 *
 * `IdeaCheckRecord` may be read outside the pool-version binding that gates `runArtifacts`
 * for exactly one reason: nothing on it is a function of the candidate pool. Until this round
 * that was a fact about the code as written, with nothing enforcing it — `ideaCheckFromPreview`
 * happened to copy five scalars, and a later edit could have added `alternatives` (a pool
 * count), `pivot` (a rejected-vs-original SCORE) or `seed_display_composite_score` with no
 * test and no type complaining.
 *
 * Widening the interface is now a tsc error (`IdeaCheckRecordIsNarrow`, proven by adding a
 * field and watching `tsc --noEmit` name it). This is the runtime half, and it is a
 * MEASUREMENT rather than a restatement of the field list: the loader is driven with the real
 * 39-key generated block and asked what came back.
 */
describe('F-5 · the idea-check record stays narrow, and it is enforced', () => {
  beforeEach(() => vi.clearAllMocks());

  it('returns exactly the sanctioned fields when handed the full pipeline block', async () => {
    mockGetPreviewReportForJob.mockResolvedValue({ idea_validation: GENERATED_BLOCK });

    const context = await loadCurrentSelectionContext(txFor(VALIDATE_JOB), 'job-1');

    expect(context?.ideaCheck).not.toBeNull();
    expect(Object.keys(context!.ideaCheck!).sort())
      .toEqual([...IDEA_CHECK_RECORD_FIELDS].sort());
  });

  it('carries none of the pool-derived values that sit beside them on the artifact', async () => {
    mockGetPreviewReportForJob.mockResolvedValue({ idea_validation: GENERATED_BLOCK });

    const context = await loadCurrentSelectionContext(txFor(VALIDATE_JOB), 'job-1');
    // Compared against the record's FIELD VALUES, not against `JSON.stringify(record)`. The
    // whole-blob form looked equivalent and was not: a leaked object arrives inside a field as
    // an escaped JSON string, which never appears verbatim in the blob. Measured — a probe
    // that stuffed `JSON.stringify(block.alternatives)` into `failureNextStep` passed the
    // blob version and fails this one.
    const values = Object.values(context!.ideaCheck!).map((v) => (v === null ? '' : String(v)));

    // Derived, not listed: every key of the real block whose value the record must not carry.
    const carried = new Set(['outcome', 'idea_name', 'user_idea_text', 'user_idea_brief',
      'headline', 'failure_next_step']);
    const leaked = Object.entries(GENERATED_BLOCK)
      .filter(([key, value]) => !carried.has(key) && value !== null && value !== undefined)
      .filter(([, value]) => {
        const asText = typeof value === 'object' ? JSON.stringify(value) : String(value);
        return asText.length > 8 && values.some((held) => held.includes(asText));
      })
      .map(([key]) => key);

    expect(
      leaked,
      leaked.length
        ? 'These pool-derived values reached a record that is read WITHOUT the pool-version '
          + `binding, which is the only thing that made the ungated read path safe:\n  ${
            leaked.join('\n  ')}`
        : undefined,
    ).toEqual([]);
    // Guards the guard: the probe must actually be the rich block, or the negative above is
    // vacuous. `alternatives`, `pivot` and `competitors` are the three the ledger names.
    expect(Object.keys(GENERATED_BLOCK).length).toBeGreaterThan(30);
    for (const pooled of ['alternatives', 'pivot', 'competitors', 'seed_display_composite_score']) {
      expect(GENERATED_BLOCK, pooled).toHaveProperty(pooled);
    }
  });

  it('is resolved for a validate run at COMPLETED, where runArtifacts are withheld', async () => {
    mockGetPreviewReportForJob.mockResolvedValue({ idea_validation: GENERATED_BLOCK });

    const context = await loadCurrentSelectionContext(txFor(VALIDATE_JOB), 'job-1');

    // The asymmetry that makes the record necessary at all (surface 19).
    expect(context?.runArtifacts.verification).toBe('untrusted');
    expect(context?.ideaCheck?.outcome).toBe(GENERATED_BLOCK.outcome);
  });

  it('is null on a discovery run — the extra read never happens', async () => {
    mockGetPreviewReportForJob.mockResolvedValue({ idea_validation: GENERATED_BLOCK });

    const context = await loadCurrentSelectionContext(
      txFor({ ...VALIDATE_JOB, entryMode: null }), 'job-1',
    );

    expect(context?.ideaCheck).toBeNull();
    expect(mockGetPreviewReportForJob).not.toHaveBeenCalled();
  });
});
