"""Captured `validate_idea` run states — one per BRANCH TUPLE through the
idea_validation block, and the loader that rebuilds them.

WHY THIS EXISTS. `fixture_056b2c68` is one captured run in two states (graded and
refused), and its drift checks are byte-exact — which is the right machinery, pointed at
too little. That run carries `incumbent_parity: "none found"`, `red_team_verdict: None`,
no typed findings, `unanchored_hypothesis: False`, `candidate_status: "active"`, an empty
`idea_ruled_out`, a `not_attempted` pivot and one anchored pain in the `limited` band. A
mutation campaign over `report/idea_validation_block.py` returned 476 survivors, and a
triage found that essentially all of the real ones are *the branches that run does not
take*: the `occupied` family (`shipped by` / `partial by` parity), the `ruled_out` family
(a demoted seed), the typed-red-team-findings path in `_kill_risks`, `_demotion_reason`,
`_display_embedded`, the pivot record, and `named_buyer_count` as an actual number rather
than `None`.

THE REMEDY IS MORE CAPTURED STATES, NOT STRONGER ASSERTIONS. Each state below is a real
run off `output/checkpoints/`, selected because its seed carries a branch tuple no other
committed fixture reaches. Each has a vendored golden block generated by calling the real
`build_idea_validation_block`, held byte-exact by `test_idea_validation_fixture.py`.

DERIVED, NEVER AUTHORED — the doctrine `test_not_evaluated_fixture_contract.py` states and
this module inherits. Nothing here is typed by hand:

  * `ideas` are the run's `stage_5_3_refinement.json::solution_ideas` VERBATIM, whole. Not
    field-selected: the 056b2c68 trim dropped `audience_fit` and `idea_ruled_out`, and the
    two consumers that read them (`_alternatives.named_buyer_count`, `_demotion_reason`)
    have been unmeasurable ever since. A trim that silently answers "None" for a field the
    producer stamps is the same class of lie as a hand-written shape.
  * `pains` keep the five fields `_anchored_pains`/`_related_pains`/`_market_signal_risk`/
    `compute_evidence_breadth` read, verbatim.
  * `posts` keep the four fields `evidence_breadth` reads (`post_id`, `author`,
    `subreddit`/`platform`, `created_utc`) — the same slice `fixture_056b2c68` keeps, and
    the reason the whole 1.5-3 MB `stage_2_social_content.json` does not have to ship.
  * `metadata` / `niche_context` are copied key-for-key off the checkpoint.

Recapture (needs `output/checkpoints/`, which is gitignored — so this is a provenance
record first and a runnable script second):

    python -m tests.unit.report.fixture_idea_check_states

Regenerate the goldens after any deliberate change to the block:

    IDEA_VALIDATION_FIXTURE_REGEN=1 pytest tests/unit/report/test_idea_validation_fixture.py
"""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from types import SimpleNamespace

STATES_DIR = (
    Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "idea_check_states"
)

# slug -> (checkpoint folder name, why this run is here)
#
# The checkpoint folder is named in full: `a_web_app_for_small_landlords…` alone resolves
# to one folder today, but `ai_visibility_for_local_businesses…` resolves to THIRTY-SEVEN
# (one real job plus 36 `prefilter-probe` re-runs), all carrying the same tuple. The job
# UUID is what makes the provenance re-derivable.
CAPTURES: dict[str, tuple[str, str]] = {
    "partial_hubdoc_killed": (
        "checkpoint_a_slack_bot_for_freelance_bookkeepers_that_automat"
        "_ecd9fcd8-45ca-4dec-82a0-ee79a161e2b3_20260808_011656",
        "parity 'partial by Hubdoc' + red_team killed (prose caveats, no typed findings) "
        "+ a REJECTED pivot record. Unlocks: outcome 'occupied' via the `partial` "
        "prefix, space_state 'partial', `_display_parity`'s subject-echo path, the "
        "pivot `trigger_finding` display branch, and a real `named_buyer_count`.",
    ),
    "shipped_idexx_weakened": (
        "checkpoint_a_browser_based_inventory_reconciliation_tool_for"
        "_e9145e2b-286e-4fc1-b23d-51e146c1c440_20260811_121311",
        "parity 'shipped by IDEXX Neo' + red_team weakened. Unlocks: the second parity "
        "spelling ('shipped' prefix -> space_state 'shipped'), and the precedence fact "
        "that a shipped parity OUTRANKS a weakened red-team verdict in "
        "`resolve_idea_validation_outcome`.",
    ),
    "demoted_rentec_ruled_out": (
        "checkpoint_a_web_app_for_small_landlords_that_reads_utility_b"
        "_16606c57-b8e1-4145-aae0-936a251731f0_20260808_180547",
        "candidate_status 'demoted' with parity 'shipped by Rentec Direct'. Unlocks the "
        "whole `ruled_out` family: the demotion branch's precedence OVER `occupied`, "
        "`seed_purchasable: False`, `_demotion_reason`, `_display_embedded`, and the "
        "verdict-trigger competitor promotion (Rentec Direct sits at index 6 of the map).",
    ),
    "typed_findings_killed": (
        "checkpoint_ai_visibility_for_local_businesses_in_london_find"
        "_03d20ff6-3973-48b6-b414-42a71883225d_20260815_153709",
        "empty parity + red_team killed carrying THREE typed `red_team_findings` "
        "(verified_incumbent_overlap, verified_free_or_bundled_alternative, "
        "evidence_gap). Unlocks the typed-findings arm of `_kill_risks`, "
        "`has_affirmative_red_team_findings`, the 'verified counterevidence' headline, "
        "and the `review_concerns` space_state that only an unprobed parity reaches.",
    ),
    "none_found_killed_unverified": (
        "checkpoint_a_chrome_extension_that_drafts_reddit_replies_for"
        "_5144763b-7715-4d47-a6c3-d8bcdcef36a1_20260807_204755",
        "parity 'none found' + red_team killed with PROSE caveats and no typed findings. "
        "Unlocks the OTHER arm of the killed headline — 'adversarial review could not "
        "confirm the premise', reached when `has_affirmative_red_team_findings` is false "
        "because the record is legacy rather than because the evidence was weak — and "
        "the legacy `red_team_caveats` fallback in `_kill_risks`. It is also the only "
        "captured pool whose `named_buyer_count` is ODD (1): see "
        "`test_a_captured_pool_carries_an_odd_named_buyer_count`.",
    ),
    "pivot_accepted_teamsnap": (
        "checkpoint_a_web_app_for_youth_soccer_coaches_that_auto_gener"
        "_f7863089-16d3-4a07-8302-e12052c9d641_20260808_120644",
        "the only captured run whose pivot was ACCEPTED: a second `user_seed` candidate "
        "under `generation_operation_id == 'validate_pivot'`. Unlocks the "
        "`pivot_idea is not None` branch (idea_id / idea_revision / name stamped onto "
        "the pivot record) — and, with `partial by TeamSnap` parity, proves the pivot "
        "candidate is still excluded from `alternatives`.",
    ),
}

# Post fields `utils/validation/evidence_breadth.py` reads. Anything else on a post is
# dead weight in a 1.5-3 MB stage_2 capture.
_POST_FIELDS = ("post_id", "author", "subreddit", "platform", "created_utc")
# Pain fields the block reads.
_PAIN_FIELDS = (
    "title", "severity_score", "mention_count", "representative_quotes", "source_post_ids",
)
_METADATA_FIELDS = (
    "user_idea_text", "user_idea_brief", "user_idea_inferred_fields", "user_idea_pivot",
    "user_idea_identity_terms", "niche_incumbent_map", "idea_ruled_out",
)
_NICHE_FIELDS = ("niche_description", "resolved_primary_audience", "user_target_audience")

_CACHE: dict[str, dict] = {}


def state_path(slug: str) -> Path:
    return STATES_DIR / f"{slug}.state.json"


def golden_path(slug: str) -> Path:
    return STATES_DIR / f"{slug}.block.generated.json"


def load_state_fixture(slug: str) -> dict:
    if slug not in _CACHE:
        _CACHE[slug] = json.loads(state_path(slug).read_text())
    return deepcopy(_CACHE[slug])


def state_from_fixture(fx: dict) -> SimpleNamespace:
    """The same state shape `fixture_056b2c68.state_from_fixture` builds, so both
    fixture families feed `build_idea_validation_block` through one contract."""
    m = fx["metadata"]
    return SimpleNamespace(
        user_idea_text=m["user_idea_text"],
        user_idea_brief=m["user_idea_brief"],
        user_idea_inferred_fields=m["user_idea_inferred_fields"],
        user_idea_pivot=m["user_idea_pivot"],
        user_idea_identity_terms=m["user_idea_identity_terms"],
        # NOT persisted on any captured checkpoint: `user_idea_brief_parity` is stamped
        # by the Q1 probe onto live state and never reached `metadata.json`. None is the
        # value every restored run carries, so it is the honest one here.
        user_idea_brief_parity=None,
        idea_generation=SimpleNamespace(
            solution_ideas=[SimpleNamespace(**i) for i in fx["ideas"]]),
        pain_point_analysis=SimpleNamespace(
            pain_points=[SimpleNamespace(**p) for p in fx["pains"]]),
        social_content=SimpleNamespace(
            reddit_posts=[SimpleNamespace(**p) for p in fx["posts_reddit"]],
            generic_posts=[SimpleNamespace(**p) for p in fx["posts_generic"]]),
        niche_context=SimpleNamespace(**fx["niche_context"]),
        niche_incumbent_map=m["niche_incumbent_map"],
        idea_ruled_out=m["idea_ruled_out"],
    )


def state_for(slug: str) -> SimpleNamespace:
    return state_from_fixture(load_state_fixture(slug))


def generate_block(slug: str) -> dict:
    """The producer call that IS each golden's provenance."""
    from nicheiq.report.idea_validation_block import build_idea_validation_block

    block = build_idea_validation_block(state_for(slug), "validate_idea")
    assert block is not None and block["outcome"] != "not_evaluated", slug
    return json.loads(json.dumps(block))


# ── capture (needs output/checkpoints/) ────────────────────────────────────────────

def _select(row: dict, fields) -> dict:
    """Present keys only — a post row carries `subreddit` OR `platform`, never both,
    and inventing the missing one would be authoring."""
    return {k: row[k] for k in fields if k in row}


def _select_all(row: dict, fields) -> dict:
    """Every key, absent ones as None — `metadata.json` omits a field it never wrote
    (`idea_ruled_out` on a run that ruled nothing out), and the restored state reads
    that as None either way."""
    return {k: row.get(k) for k in fields}


def capture(slug: str, checkpoint_root: Path) -> dict:
    folder, why = CAPTURES[slug]
    src = checkpoint_root / folder
    meta = json.loads((src / "metadata.json").read_text())
    niche = json.loads((src / "stage_1_niche_context.json").read_text())
    pains = json.loads((src / "stage_3_pain_points.json").read_text())
    ideas = json.loads((src / "stage_5_3_refinement.json").read_text())
    social = json.loads((src / "stage_2_social_content.json").read_text())

    pain_rows = pains["pain_points"] if isinstance(pains, dict) else pains
    return {
        "_provenance": {
            "checkpoint": folder,
            "job_id": folder.rsplit("_", 3)[-3],
            "entry_mode": meta.get("entry_mode"),
            "why": why,
            "trim": (
                "ideas: stage_5_3_refinement.json::solution_ideas VERBATIM (whole rows). "
                "pains: " + ", ".join(_PAIN_FIELDS) + ". "
                "posts: " + ", ".join(_POST_FIELDS) + " — the fields "
                "utils/validation/evidence_breadth.py reads. "
                "metadata/niche_context: copied key-for-key."
            ),
            "recapture": "python -m tests.unit.report.fixture_idea_check_states",
        },
        "metadata": _select_all(meta, _METADATA_FIELDS),
        "niche_context": _select_all(niche, _NICHE_FIELDS),
        "ideas": ideas["solution_ideas"],
        "pains": [_select(p, _PAIN_FIELDS) for p in pain_rows],
        "posts_reddit": [_select(p, _POST_FIELDS) for p in (social.get("reddit_posts") or [])],
        "posts_generic": [_select(p, _POST_FIELDS) for p in (social.get("generic_posts") or [])],
    }


def main() -> None:  # pragma: no cover — provenance script, not a test
    root = Path(__file__).resolve().parents[3] / "output" / "checkpoints"
    STATES_DIR.mkdir(parents=True, exist_ok=True)
    for slug in CAPTURES:
        payload = capture(slug, root)
        state_path(slug).write_text(json.dumps(payload, indent=1) + "\n")
        print(f"captured {slug}: {state_path(slug)}")


if __name__ == "__main__":  # pragma: no cover
    main()
