"""The refused-run block, GENERATED from the real builder and vendored for the frontend.

WHY THIS EXISTS. `frontend/.../validateNotEvaluatedSurface.test.ts` used to hand-write the
refused `idea_validation` block. Its author wrote `experiment_ladder: []` — a shape
`build_idea_validation_block` CANNOT produce, because the ladder and the desk limits are
stamped on every block before the `seed is None` refusal branch is even reached. Three
rounds of assertions about the refused report page therefore rendered an empty `<ol>` and
passed vacuously, and the sixteenth surface (a four-rung experiment ladder prescribed for
an idea that was never graded) survived every one of them.

The durable property is not "this fixture is correct today". It is **this fixture is a
shape the pipeline can actually produce**, and the only way to hold that is to stop
authoring it by hand. So the committed JSON below is generated by calling the real builder
on the real captured 056b2c68 run state with its seed marker removed — the exact state a
refusal leaves behind: Phase 1 research completed and wrote pains, posts and a candidate
pool; the seed pipeline refused, so no `generation_operation_id == "validate"` idea exists.

Regenerate after any deliberate change to the refused block:

    IDEA_VALIDATION_FIXTURE_REGEN=1 pytest tests/unit/report/test_not_evaluated_fixture_contract.py

and commit the JSON. Any other drift between the two fails here, in Python, where the
change is being made — not silently in a frontend suite that has no way to know.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from nicheiq.report.idea_validation_block import (
    SEED_FAILURE_COPY,
    SEED_FAILURE_GENERIC,
    SEED_FAILURE_GENERIC_NEXT,
    build_idea_validation_block,
)

from .fixture_056b2c68 import load_fixture, state_from_fixture

_FIXTURE_DIR = (
    Path(__file__).resolve().parents[3]
    / "frontend" / "src" / "lib" / "components" / "__tests__" / "fixtures"
)
VENDORED_PATH = _FIXTURE_DIR / "ideaValidationNotEvaluated.generated.json"
# The same run, GRADED. Vendored for two reasons: the frontend control assertions ("the fix
# withholds these cards, it does not delete them") need a real graded block, and the
# pre-2026-08-14 legacy artifact — a refusal that still inherited the base stamp — is
# reconstructed from these three real fields rather than hand-typed a third time.
VENDORED_GRADED_PATH = _FIXTURE_DIR / "ideaValidationGraded.generated.json"

# The typed refusal cause used for the vendored fixture. `identity_judge_unavailable` is the
# purest "ours, not yours" cause: nothing about the submitted text contributed to it, so any
# page copy that implies the user should change something is unambiguously wrong against it.
FAILURE_REASON = "identity_judge_unavailable"

# ROUND 11 (G-3) — EVERY REFUSAL SENTENCE THE PIPELINE CAN PUT IN FRONT OF A USER.
#
# The frontend used to police hand-authored refusal copy with a KEYWORD BLACKLIST
# ("rephras", "reword", "rewrit", …). This program's whole finding is that an enumerated
# vocabulary loses to the next spelling — the same list had already lost to an inflection
# once, inside the assertion that states the lesson. It is unfixable by lengthening:
# `re-word`, `reformulate`, `restate`, "be more specific" and "clarify your description"
# all walk through, and the next one nobody thought of walks through too.
#
# The property that does not need a vocabulary is the one already used for the block
# itself: a refusal sentence in a spec must be a sentence the PRODUCER can emit. That set
# is closed and it lives here, so it is vendored the same way the blocks are and the
# frontend can hold a spec to it. A sentence blaming the user is then unwritable not
# because a list forbids those words, but because no cause carries it.
VENDORED_COPY_PATH = _FIXTURE_DIR / "seedFailureCopy.generated.json"

# NOT vendored: the refused-run block for a pool that ALSO carries a chat seed. Once the
# user's own idea is excluded from `alternatives` it is byte-identical to the plain
# refused block — which is the whole point — so a fourth JSON file would be a duplicate
# the frontend cannot tell apart from the third. The property is held by
# `test_the_chat_seed_changes_nothing_else_about_the_refused_block` instead, where it is
# an assertion rather than a file.

# The operation id `worker/tasks.py::run_seed_idea` stamps on a chat-born candidate
# (`idea.generation_operation_id = seed_operation_key`, where the key is the paid
# `seed_idea_N` dispatch). The one thing that distinguishes it from the validate seed.
CHAT_SEED_OPERATION_ID = "seed_idea_1"


def _chat_seeded_candidate(fx: dict) -> dict:
    """The user's own idea, minted by the CHAT seed endpoint on a REFUSED validate run.

    This state is reachable and was recorded as a forward hazard by `_find_marked` before
    it was closed: `POST /api/jobs/:jobId/seed` has no `entryMode` check, so a subscribed
    user whose `validate_idea` run refused can pay again to seed the SAME pitch from chat
    at AWAITING_SELECTION. `run_seed_idea` appends it to the pool with
    `source_frame == "user_seed"` (from the crew's seed cell) and
    `generation_operation_id == "seed_idea_N"` — so `_find_marked`, which keys on the
    `validate` operation id, correctly does not find it, and the run's report block still
    says `not_evaluated`.

    DERIVED, never authored: this is the run's OWN captured `user_seed` candidate with the
    two fields the chat path stamps differently. A hand-written candidate would be a shape
    the pipeline cannot emit — the trap that cost this program three rounds of vacuous
    frontend assertions. Same pitch, same fields, different paid operation, which is
    exactly the case the user hits.
    """
    seed = next(i for i in fx["ideas"]
                if (i.get("source_frame") or "").strip().lower() == "user_seed"
                and i.get("generation_operation_id") == "validate")
    chat_seed = dict(seed)
    chat_seed["generation_operation_id"] = CHAT_SEED_OPERATION_ID
    # `stamp_new_idea_identities` mints a fresh identity for the chat-born idea.
    chat_seed["idea_id"] = "chat-seed-0001"
    return chat_seed


def generate_not_evaluated_with_chat_seed_block() -> dict:
    """The refused block for a run that carries a chat-seeded copy of the user's pitch.

    `run_seed_idea` appends (`merged_solutions = old_solutions + [idea]`), so the chat
    seed is LAST in the pool — which is why it inflated `alternatives.count` on every run
    but only reached `top` when fewer than five other candidates were active.
    """
    fx = load_fixture()
    fx["ideas"] = [i for i in fx["ideas"]
                   if i.get("generation_operation_id") != "validate"]
    fx["ideas"].append(_chat_seeded_candidate(load_fixture()))
    state = state_from_fixture(fx)
    state.user_idea_failure_reason = FAILURE_REASON
    block = build_idea_validation_block(state, "validate_idea")
    assert block is not None and block["outcome"] == "not_evaluated"
    return json.loads(json.dumps(block))


def generate_not_evaluated_block() -> dict:
    """The refused block, from the real builder. This call IS the fixture's provenance."""
    fx = load_fixture()
    # A refusal means the seed pipeline never produced the user's idea, so no candidate
    # carries the "validate" marker. Everything else the live run captured stays.
    fx["ideas"] = [i for i in fx["ideas"]
                   if i.get("generation_operation_id") != "validate"]
    state = state_from_fixture(fx)
    state.user_idea_failure_reason = FAILURE_REASON
    block = build_idea_validation_block(state, "validate_idea")
    assert block is not None and block["outcome"] == "not_evaluated"
    return json.loads(json.dumps(block))


def generate_graded_block() -> dict:
    """The same captured run, graded — the control the refused fixture is measured against."""
    block = build_idea_validation_block(state_from_fixture(), "validate_idea")
    assert block is not None and block["outcome"] != "not_evaluated"
    return json.loads(json.dumps(block))


def _check(path: Path, generated: dict) -> None:
    if os.environ.get("IDEA_VALIDATION_FIXTURE_REGEN"):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(generated, indent=2) + "\n")

    assert json.loads(path.read_text()) == generated, (
        f"The vendored fixture the frontend renders ({path.name}) has drifted from what "
        f"build_idea_validation_block actually emits. Regenerate it:\n  "
        f"IDEA_VALIDATION_FIXTURE_REGEN=1 pytest tests/unit/report/{Path(__file__).name}\n"
        "Do NOT hand-edit the JSON: a hand-authored shape the pipeline cannot produce is "
        "exactly what made three rounds of refused-page assertions pass vacuously."
    )


def test_vendored_frontend_fixture_matches_the_real_builder():
    _check(VENDORED_PATH, generate_not_evaluated_block())


def test_vendored_graded_fixture_matches_the_real_builder():
    _check(VENDORED_GRADED_PATH, generate_graded_block())


def generate_seed_failure_copy() -> dict:
    """The complete refusal register: every typed cause's pair, plus the generic fallback.

    Read off `SEED_FAILURE_COPY` itself rather than off the causes some test happens to
    exercise — a cause added tomorrow is vendored the moment this regenerates, and until it
    does the drift assertion below is what says so.
    """
    copy = {
        cause: {"headline": entry.headline, "next_step": entry.next_step}
        for cause, entry in SEED_FAILURE_COPY.items()
    }
    copy["__generic__"] = {
        "headline": SEED_FAILURE_GENERIC,
        "next_step": SEED_FAILURE_GENERIC_NEXT,
    }
    return copy


def test_vendored_seed_failure_copy_matches_the_producer():
    _check(VENDORED_COPY_PATH, generate_seed_failure_copy())


def test_refusal_prescribes_no_experiments_and_caveats_no_findings():
    """The sixteenth surface, pinned at the artifact.

    A refused run graded nothing, so it has nothing to caveat and no verdict to run the
    next-cheapest test against. Rung 1 ("Run 5 problem interviews with the buyer you
    named") costs the reader a week of work on an idea this run never evaluated, and two
    of the three desk limits caveat content that is empty on a refusal — commitment
    evidence "for this idea", and severity/mention counts that live in `anchored_pains`
    and `breadth`, both of which the refusal branch clears.
    """
    block = generate_not_evaluated_block()
    assert block["experiment_ladder"] == []
    assert block["next_experiment_index"] is None
    assert block["desk_limits"] == []
    # `provisional` hedges a verdict that could still upgrade. There is no verdict.
    assert block["provisional"] is False


# ── the user's own idea is never one of the market's alternatives ──────────────────
#
# `alternatives` is what the page calls "approaches from this market's evidence", under a
# sentence reading "None of them is your idea". `_alternatives` used to enforce that by
# excluding the two candidates `_find_marked` returns, and `_find_marked` keys on the
# OPERATION id — a property it documented that it does NOT provide. So a chat-seeded copy
# of the user's own pitch was counted as market evidence on the page telling them nothing
# of theirs had been graded.

def _chat_seed_pool_variant(*, refuse: bool):
    """The same pool, with the chat seed, built through the refused or the graded branch."""
    fx = load_fixture()
    if refuse:
        fx["ideas"] = [i for i in fx["ideas"]
                       if i.get("generation_operation_id") != "validate"]
    fx["ideas"].append(_chat_seeded_candidate(load_fixture()))
    state = state_from_fixture(fx)
    state.user_idea_failure_reason = FAILURE_REASON
    return json.loads(json.dumps(build_idea_validation_block(state, "validate_idea")))


def test_a_chat_seed_is_not_counted_among_the_market_alternatives():
    """The defect, on the branch it was reported on."""
    block = generate_not_evaluated_with_chat_seed_block()
    alternatives = block["alternatives"]
    # 10 is the live run's own alternatives count; the chat seed must not make it 11.
    assert alternatives["count"] == 10
    assert all(row["idea_id"] != "chat-seed-0001" for row in alternatives["top"])


def test_the_graded_branch_excludes_a_chat_seed_on_the_same_terms():
    """The asymmetry guard. Both call sites read ONE predicate, so a fix that reached the
    refused branch alone is not expressible — but only a measurement says so, and this
    program has been caught before by a fix that was right on one path of two."""
    refused = _chat_seed_pool_variant(refuse=True)
    graded = _chat_seed_pool_variant(refuse=False)
    assert refused["outcome"] == "not_evaluated"
    assert graded["outcome"] != "not_evaluated"
    assert graded["alternatives"] == refused["alternatives"]
    assert graded["alternatives"]["count"] == 10


def test_the_chat_seed_changes_nothing_else_about_the_refused_block():
    """Scope. Excluding the user's idea from ONE pool must not perturb the rest of the
    block — and, read the other way, this is what makes the `alternatives` delta above
    the whole of the defect rather than a symptom of a larger one."""
    with_chat_seed = generate_not_evaluated_with_chat_seed_block()
    without = generate_not_evaluated_block()
    assert with_chat_seed == without


def test_named_buyer_count_excludes_the_users_own_idea_and_stays_inconclusive_when_blind():
    """`named_buyer_count` derives from the SAME pool, so it moved with the count: the
    user's own idea was reported back to them as one of the alternatives that "primarily
    serve the buyer you named". Its None-when-nothing-was-judged semantics are the other
    half — an empty pool of verdicts must stay inconclusive, never collapse to 0."""
    fx = load_fixture()
    fx["ideas"] = [i for i in fx["ideas"]
                   if i.get("generation_operation_id") != "validate"]
    chat_seed = _chat_seeded_candidate(load_fixture())
    fx["ideas"].append(chat_seed)
    # The run's audience-fit pass judged nothing for the buyer the user named EXCEPT the
    # user's own idea — the case where the sentence would be entirely about their pitch.
    for idea in fx["ideas"]:
        idea["audience_fit"] = idea["idea_id"] == chat_seed["idea_id"]
    state = state_from_fixture(fx)
    state.user_idea_failure_reason = FAILURE_REASON
    judged = build_idea_validation_block(state, "validate_idea")["alternatives"]
    assert judged["count"] == 10
    assert judged["named_buyer_count"] == 0, (
        "the only audience_fit=True candidate is the user's own idea")

    # Legacy run: no candidate carries an audience_fit verdict at all -> inconclusive.
    assert generate_not_evaluated_with_chat_seed_block()["alternatives"][
        "named_buyer_count"] is None


def test_the_pool_is_not_starved_on_an_ordinary_validate_run():
    """Do not over-exclude. `source_frame == "user_seed"` is minted by the validate seed,
    the parity pivot and the chat seed path — never by a discovery frame
    (`unified_solution_crew` dispatches every frame except `pain` and `user_seed`, and
    only `_run_seed_cell` submits the latter). So on a run with no chat seed the fix must
    remove exactly nothing, on BOTH branches, byte for byte."""
    assert generate_not_evaluated_block()["alternatives"]["count"] == 10
    assert generate_graded_block()["alternatives"]["count"] == 10
    assert (generate_not_evaluated_block()["alternatives"]
            == generate_graded_block()["alternatives"])


def test_graded_run_keeps_the_full_ladder_and_limits():
    """The control: the fix withholds these from a refusal, it does not delete the feature.

    Without this, emptying the three fields unconditionally would also pass.
    """
    from nicheiq.report.idea_validation_block import DESK_LIMITS, EXPERIMENT_LADDER

    graded = generate_graded_block()
    assert graded["desk_limits"] == list(DESK_LIMITS)
    assert graded["experiment_ladder"] == [dict(r) for r in EXPERIMENT_LADDER]
    assert graded["next_experiment_index"] == 0
    assert graded["provisional"] is True
