"""The FinalReport, GENERATED from the real ReportGenerator and vendored.

WHY THIS EXISTS. `ReportGenerator` is constructed in 23 unit-test files. All 23 hand-build
its state with `MagicMock()` or `SimpleNamespace`, and none of them calls
`_assemble_base_report()` or `generate_report()` — so the 63-field artifact the SvelteKit
report page renders, and that `frontend/src/lib/types/report.ts` claims to mirror, has
never once been produced inside the suite. That is the same generator that already cost
this repo six rounds of vacuous assertions on `idea_validation`: the tests pin the author's
belief about a producer's shape instead of the producer's output. A `MagicMock` state makes
it worse than a hand-written dict, because every attribute the assembler reads exists and
is truthy, so a `ResearchState` field renamed out from under the report cannot fail
anything.

The durable property is the same one `test_not_evaluated_fixture_contract.py` holds for the
refused idea-validation block: **this fixture is a shape the pipeline can actually
produce**. It is generated by running the real producer over the real captured 8f35ea6b run
state, restored through the real `CheckpointManager` (see `report_run_8f35ea6b.py`).

Regenerate after any deliberate change to the report:

    REPORT_FIXTURE_REGEN=1 pytest tests/unit/report/test_final_report_fixture_contract.py

and commit the JSON. Any other drift fails here, in Python, where the change is being made.

WHAT IS NOT COVERED, AND WHY. `generate_report()` itself cannot be driven offline. Its
step-2 strategic synthesis is three `LLMService.invoke_structured` calls, and the three
step-3 producers `_generate_executive_dashboard` (8.5s), `_generate_analytics` (19s) and
`_generate_gtm_blueprint` (41s) all reach the network before their fail-soft fallbacks
return. Their timings are the retry ladder, not compute. Vendoring them would mean either
mocking the LLM — at which point the artifact records the mock's shape, which is the defect
this file exists to remove — or a ~70s network-dependent unit test. They are named here as
an uncovered surface rather than faked. `ExecutiveDashboard` in particular is still pinned
only by `MagicMock` states in `test_verdict_never_silently_dropped.py`.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from nicheiq.report.report_generator import ReportGenerator

from .report_run_8f35ea6b import load_state

_FIXTURE_DIR = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "generated"
VENDORED_BASE_PATH = _FIXTURE_DIR / "finalReportBase.generated.json"
VENDORED_BLOCKS_PATH = _FIXTURE_DIR / "finalReportBlocks.generated.json"

# `_assemble_base_report` stamps wall-clock time. It is the ONLY non-deterministic field in
# the artifact — two builds from the same restored state are otherwise byte-identical — so
# it is dropped rather than frozen, and the fact that it is the only one is asserted below.
NONDETERMINISTIC_FIELDS = ("generated_at",)


def _build(tmp_path) -> tuple[dict, dict]:
    """Run the real report producers over the real restored run state.

    Order mirrors `generate_report()` exactly: assemble, then step 1.5 community-hub
    enrichment (which MUTATES the report in place), then the step-3 producers that do not
    call an LLM. Reproducing the orchestration order matters — `_enrich_community_hubs`
    runs against the assembled report, not against the state.
    """
    generator = ReportGenerator(load_state(tmp_path))
    report = generator._assemble_base_report()
    generator._enrich_community_hubs(report)

    base = report.model_dump(mode="json")
    for field in NONDETERMINISTIC_FIELDS:
        base.pop(field, None)

    blocks = {
        "research_metadata": generator._generate_research_metadata().model_dump(mode="json"),
        "data_quality_summary": generator._generate_data_quality_summary().model_dump(
            mode="json"
        ),
        "alternative_solutions": [
            alternative.model_dump(mode="json")
            for alternative in generator._generate_alternative_solutions()
        ],
    }
    return base, blocks


def _check(path: Path, generated: dict | list) -> None:
    if os.environ.get("REPORT_FIXTURE_REGEN"):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(generated, indent=2, sort_keys=True) + "\n")

    assert json.loads(path.read_text()) == generated, (
        f"The vendored report fixture ({path.name}) has drifted from what ReportGenerator "
        f"actually emits for the captured 8f35ea6b run. Regenerate it:\n  "
        f"REPORT_FIXTURE_REGEN=1 pytest tests/unit/report/{Path(__file__).name}\n"
        "Do NOT hand-edit the JSON. A hand-authored shape the pipeline cannot produce is "
        "exactly what made three rounds of refused-page assertions pass vacuously, and a "
        "MagicMock report state is the same defect with the shape hidden instead of wrong."
    )


def test_vendored_base_report_matches_the_real_assembler(tmp_path):
    base, _ = _build(tmp_path)
    _check(VENDORED_BASE_PATH, base)


def test_vendored_report_blocks_match_the_real_producers(tmp_path):
    _, blocks = _build(tmp_path)
    _check(VENDORED_BLOCKS_PATH, blocks)


def test_the_only_unstable_field_is_the_wall_clock_stamp(tmp_path):
    """Guards the drop-list above. If the assembler acquires a second non-deterministic
    field — a uuid, a dict ordered by set iteration — this fails instead of the vendored
    fixture becoming un-regenerable and someone widening `NONDETERMINISTIC_FIELDS` to make
    the red go away."""
    first, _ = _build(tmp_path / "a")
    second, _ = _build(tmp_path / "b")
    assert first == second


def test_the_captured_corpus_is_load_bearing_in_full(tmp_path):
    """Why nothing in the vendored checkpoint is trimmed, as an assertion.

    A smaller fixture is tempting at 2MB. But both counting blocks read the corpus length,
    so any trim silently rewrites the artifact — the fixture would stop being this run's
    output and start being a smaller run that never happened. This ties the artifact to the
    stage-2 file so a future trim fails here rather than regenerating quietly.
    """
    state = load_state(tmp_path)
    corpus = len(state.social_content.reddit_posts)
    _, blocks = _build(tmp_path / "b")
    assert corpus == 116
    assert blocks["research_metadata"]["reddit_posts_analyzed"] == corpus


def test_the_assembler_leaves_the_llm_and_step_three_fields_unset(tmp_path):
    """The two-phase contract, read off the real producer.

    `_assemble_base_report` is documented as "80% of the work"; the rest is filled by
    step 2 (LLM) and step 3. Which fields belong to which phase is exactly the sort of
    thing a hand-built `FinalReport` gets wrong in the permissive direction — a MagicMock
    report has `executive_dashboard` populated at assembly time, which no real run does.
    """
    base, _ = _build(tmp_path)
    for field in (
        "executive_dashboard",
        "go_to_market_blueprint",
        "market_analytics",
        "seo_analytics",
        "competitive_analytics",
        "pain_point_analytics",
        "research_metadata",
        "data_quality_summary",
        "site_structure",
        "user_flows",
    ):
        assert base[field] is None, (
            f"{field} is populated by generate_report() after assembly, not by the "
            "assembler. If that moved, the vendored fixture and this list both need it."
        )
    # The control: assembly is not simply returning an empty shell.
    assert base["selected_solution_name"]
    assert base["detailed_pain_points"]
    assert base["recommended_solutions"]
